### ISSUE TITLE
Greenflame Blade and elemental adept

### ISSUE THREAD

**Issue by Neonuzzer** [kakaroto/Beyond20#670] opened 2021-01-30 14:37 UTC
**Describe the bug**
Greenflame Blade will not appropriately apply Elemental Adept (Fire) if you "use it" as part of the weapon attack in DND beyond.

**To Reproduce**
1. Create a character with an equipped weapon and the cantrip greenflame blade
2. Click on the equipped weapon in the "Actions" tab
3. Scroll down to Green-flame Blade in the weapon panel that appears and click the Beyond 20 button
4. When clicked, it will roll the weapon attack, the weapon damage, and green-flame cantrip damage

**Expected behavior**
It should roll change Green-flame blade damage to 2 if the die is 1, but it doesn't.  It will correctly do so if you click Green-flame blade under the spells tab, but that won't roll the weapon damage with the Green-Flame Blade damage.

**Screenshots**
1. Where on character sheet I use
![image](https://user-images.githubusercontent.com/78266172/106359092-57c93d00-62de-11eb-9acd-cc9c1783370d.png)
2. rolled damage
![image](https://user-images.githubusercontent.com/78266172/106359104-6d3e6700-62de-11eb-9d66-9ce09db642fa.png)
3. Showing what the elemental adept should be doing on the produce flame spell but not on the green-flame blade spell
![image](https://user-images.githubusercontent.com/78266172/106359124-94953400-62de-11eb-9261-afe5aee67ae7.png)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 88.0.4324.104 (Official Build) (64-bit)

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by Aeristoka** [comment] 2021-01-30 14:38
Duplicate of #650 , will be handled by changes in accordance with #658

**Closed by Aeristoka** 2021-01-30 14:38 UTC
Labels: bug
