### ISSUE TITLE
Character specific settings randomly not saving.

### ISSUE THREAD

**Issue by rand0mchance** [kakaroto/Beyond20#505] opened 2020-08-31 01:46 UTC
Noticing an issue where I try to set custom damage or change weapon rolls to be one-handed only under the Character Specific settings, the settings aren't saved after I close the screen - they just reset back to the default.  It isn't happening on all characters and although I've tried to find something common to when it happens and when it does not, I've been unable to thusfar.

**Comment by rand0mchance** [comment] 2020-08-31 02:22
I *can* say that I've deleted and remade one of my characters multiple times and I see the issue every time I try to do char specific settings on a rogue/warlock combo.

**Comment by Aeristoka** [comment] 2020-08-31 02:35
![image](https://user-images.githubusercontent.com/7988297/91677540-44802e80-eb00-11ea-8339-b278b034ad0f.png)

Set it from here, it will stick (or you might have to try removing/re-adding the extension, there is a standing bug with settings just not sticking sometimes, being looked at).

**Comment by kakaroto** [comment] 2020-08-31 05:27
This is probably a duplicate of #135. The only clue I've found as to the cause was this recent report : #502 
Still can't reproduce it or figure out why it happens.

**Comment by rand0mchance** [comment] 2020-08-31 14:21
Thanks for the fast response.  Sorry for not catching the other ticket, I
looked for one in an effort to not make a duplicate, but apparently I
didn't look close enough.
The button you suggested is the button I normally use when
setting/unsetting things from the Character Specific settings, so that
isn't it, but I will try removing and re-adding the extension.  It's weird
that it only does this for certain characters, I might go through some
permutations of single class/multiclass to see if there is any combination
that always shows the issue.
Thanks again though for all of the work - the app is fantastic.

Daniel

**Closed** 2020-09-12 00:41 UTC
