### ISSUE TITLE
Use permissions.request and make permissions less broad on FF

### ISSUE THREAD

**Issue by Jonfor** [kakaroto/Beyond20#179] opened 2020-04-10 04:56 UTC
The permissions for Firefox seem to include "Access your data for all websites" instead of the permissions specified in the Firefox manifest. Chrome displays the specific website permissions correctly. I've attached images of both below.

I'm not sure why this is different, the only difference I see in permissions storage:

Firefox -> "*://*/*game"
Chrome -> "*://*.forgevtt.com/game",
		  "*://*.forge-vtt.com/game",
                  "*://beyond20.kicks-ass.org/roll",

Any idea why Firefox seems to be displaying the permissions requested incorrectly?

![Capture](https://user-images.githubusercontent.com/3246528/78963387-4dc31d00-7ac5-11ea-87a5-88f2e7410da5.PNG)

![Capture](https://user-images.githubusercontent.com/3246528/78963513-b1e5e100-7ac5-11ea-98db-8dbca68d0003.PNG)

**Comment by kakaroto** [comment] 2020-04-10 05:44
The FF manifest is here : https://github.com/kakaroto/Beyond20/blob/master/manifest_ff.json (which I rename before bundling it for release on FF)
And the permissions, as you can see, are : 
```json
	"permissions": [
		"activeTab",
		"tabs",
		"storage",
		"*://app.roll20.net/editor/",
		"*://*.dndbeyond.com/*",
		"*://*/*game"
	],
```
As you can see, there's a "*" permission in there for the host, which is why it asks for all sites.

The reason for that permission is because Foundry VTT is self hosted, so it can be on any URL, or any IP address, and accessing all sites is necessary to detect and work on Foundry VTT in Firefox.
In Chrome, things are different because Chrome changed things to make it harder to get reviewed when asking for broad permissions like that (multiple weeks before an update gets reviewed and released on the store).
For chrome it's more annoying to FVTT users since players have to click the beyond20 icon in the address bar every time they load/reload their Foundry VTT page in order to 'activate' it, and it's one of the biggest annoyances with the extension.
I've explained it all on the release notes of v0.5 where the change happened : https://beyond20.here-for-more.info/release_notes#v05

As for "what does the extension do on all sites", this is the script that gets loaded : https://github.com/kakaroto/Beyond20/blob/master/src/fvtt_test.js
It does a single thing, if the title of the page is "Foundry Virtual Table Top", then it activates the icon, which will then load the FVTT content script. Otherwise, it does nothing.
This separation and minimal code hopefully helps people who get worried about the broad permissions in Firefox. I do not however plan on making them stricter... I'm actually contemplating making it broader for Chrome even if it means an update gets rejected or it takes weeks to get approved.

I hope that answers all your questions. 
Regardless, firefox isn't displaying the permissions incorrectly, but I'm going to keep this issue open though, and tag it to make this explanation part of the FAQ.

**Comment by Jonfor** [comment] 2020-04-10 22:45
Thank you for the the thorough explanation! Adding it to the FAQ somewhere would be helpful. Thanks again.

**Comment by moritonal** [comment] 2020-05-18 19:10
Would we be able to support dynamic permissions using [permissions.request](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request)? 

If so I'm happy to put a PR together?

**Comment by kakaroto** [comment] 2020-05-19 22:19
I don't know, I hadn't seen that API. If there's a way for it to find when a new tab is opened to a Foundry page (i.e: using the 'tabs' permission already, so I think I can already list tab names/urls, and I expect there would be a notification sort of event when new tabs open or tabs change their URL), then yeah, the background script could detect the `*/game` urls and check the title for Foundry VTT then request the permission for that tab/url specifically. Don't know how that would work, but I'd love to have that if it works as intended.
A PR would be much appreciated :)

**Comment by kakaroto** [comment] 2020-05-27 02:11
So, I looked at the `permissions.request` API and it looks like it can only be called on user action (i.e: when they click on the beyond20 icon in the address bar). However, the cool thing about it, is that you only need to do it once, and the new permission gets saved, instead of having to do it on every reload.
This makes the user experience much better, and I love it!

**However**, I spent some time trying to make it work and I just can't figure it out. It looks like the optional permissions still says the extension requires permissions to read everything. It also seems to keep the permission for the tab on reload, but not if you open the same url in a different tab. And reloading the extension seems to clear away all those permissions. I don't know if being in development mode is affecting it, but I got really confused at trying to get a good behavior out of this.

If we can get this to work the way that it should, then I'll change the Firefox behavior to be similar to Chrome, so you only need to activate the extension manually once per site, and you're done. 
Thanks @moritonal for showing me that API! Now let's try to get it to work! :)

**Comment by kakaroto** [comment] 2020-05-29 03:37
I've renamed this to make use of permissions.request, which I think is great and will allow us to not have the permissions so broad anymore. Shouldn't need to explain in FAQ something that's about to be removed. But I'm bumping this for the 2.1 release instead.

**Comment by MicahZoltu** [comment] 2020-07-19 23:03
I don't know what the timeline is like on the proposed `permissions.request` change, but in the meantime would it be possible to get a release published that doesn't require all-sites permissions?

As a developer, I can load the add-on manually from source code until the issue gets resolved, but other people I play with are not savvy enough to do that and I am uncomfortable recommending an add-on to them that requires all-sites permissions.  Since we will be playing with Roll20, the wildcard access isn't necessary so there is no UX concern around having to click the icon for our group.

If you think the `permissions.request` stuff will be included "soon", then it probably isn't worth publishing an alternative version, but if that feature is still some time away then an alternative version published that doesn't require all-sites permission would be a valuable addition.

**Comment by kakaroto** [comment] 2020-07-20 03:05
> I don't know what the timeline is like on the proposed `permissions.request` change, but in the meantime would it be possible to get a release published that doesn't require all-sites permissions?
> 
> As a developer, I can load the add-on manually from source code until the issue gets resolved, but other people I play with are not savvy enough to do that and I am uncomfortable recommending an add-on to them that requires all-sites permissions. Since we will be playing with Roll20, the wildcard access isn't necessary so there is no UX concern around having to click the icon for our group.
> 
> If you think the `permissions.request` stuff will be included "soon", then it probably isn't worth publishing an alternative version, but if that feature is still some time away then an alternative version published that doesn't require all-sites permission would be a valuable addition.

As a developer, I'd appreciate the help if you were to implement and test the `permissions.request` behavior and send that as a pull request. 
I will not however be publishing a separate release without the full permissions nor will I temporarily disable it and break the UX for a major portion of the users. As a developer, you could also review the 1 line of code script that gets loaded and confirm that it's not malicious and tell your players that it's safe.

**Comment by kakaroto** [comment] 2021-12-25 22:24
Getting this to work properly was complicated, but I got it. After adding the `<all_urls>` to `optional_permissions`, I was able to do the request and get it to behave correctly, as long as I did the request in a click handler (can't do it on a browser or page action handler for example). 
On top of that, I had to **not** add the content scripts in the manifest to inject on those urls, instead the background page had to query for all tabs and listen for tab update notifications to find when a newly-permitted url was accessed and programmatically inject the content scripts into it. If we add it to the manifest, it was causing the issue that it would get injected but with a limited sandbox/scope so some APIs wouldn't work, and that caused the misbehavior I was seeing before.
I've pushed this to a separate branch for now. I need to do more testing and then it should be ready to merge.

**Closed** 2021-12-27 20:09 UTC
