### ISSUE TITLE
 The crimson rite ability now rolls 1d41d4 dice instead of only 1d4

### ISSUE THREAD

**Issue by XRamusX** [kakaroto/Beyond20#811] opened 2021-06-03 22:13 UTC
**Describe the bug**
 The crimson rite ability now rolls 1d41d4 dice instead of only 1d4. Also there is one dice button missing next to one of the fromulas.
**To Reproduce**
1. Go to a blood hunter character
2. Click on the crimson rite formulas without clicking on the tab in on the right , just on the actions tab
3. See error

**Expected behavior**
It should roll the normal ammount not 1d41d4

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.
![errorbeyond20](https://user-images.githubusercontent.com/64174699/120718462-fc000200-c4d1-11eb-92f2-23303ea29158.png)

**Browser Info (please complete the following information):**
 - Browser [e.g. chrome, firefox] Chrome
 - Version [e.g. 85] 2.4.3
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by Aeristoka** [comment] 2021-06-03 22:14
Duplicate of #807

**Closed by Aeristoka** 2021-06-03 22:14 UTC
Labels: bug

**Comment by kakaroto** [comment] 2021-06-05 03:45
(To be fair, this is a better written issue than the one I created 😜 )
Thanks for the report! Working on it right now! 👍

**Comment by XRamusX** [comment] 2021-06-05 04:24
> (To be fair, this is a better written issue than the one I created 😜 )
> Thanks for the report! Working on it right now! 👍

Thanks man , happy to help and keep up the amazing work you guys are doing !

**Comment by Aeristoka** [comment] 2021-06-05 04:25
> (To be fair, this is a better written issue than the one I created 😜 )
> Thanks for the report! Working on it right now! 👍

Isn't everything?
