### ISSUE TITLE
Cannot connect to Roll20 VTT

### ISSUE THREAD

**Issue by sdnicol** [kakaroto/Beyond20#1072] opened 2023-07-07 13:25 UTC
Since the latest update D&D Beyond does not recognize that a Roll20 VTT window is open and active.
Using Firefox 114.0.2. I tried on both my Windows and Mac.

**Comment by Aeristoka** [comment] 2023-07-07 13:26
Duplicate of #1071 

Beyond20 2.9.1 has been created, available on Chrome Store, but not Firefox or Edge stores yet.

**Closed** 2023-07-07 13:26 UTC

**Comment by sdnicol** [comment] 2023-07-07 13:27
Understood. Thanks man.

**Comment by Aeristoka** [comment] 2023-07-07 13:30
It's only the second time the Firefox store has needed approvals (after 2.9.1), but it also means it's real inconvenient when Roll20 has screwed us like this, so much that it requires a new Beyond20 version to work around their nonsense.
