### ISSUE TITLE
Features & Traits Tabs Showing Multiple Dice

### ISSUE THREAD

**Issue by rokeefe-UF** [kakaroto/Beyond20#247] opened 2020-05-08 03:40 UTC
The Features and Traits tab on load shows no beyond20 dice near a bonus to a roll. However when clicking a feature, it adds dice to the bonuses and when clicking multiple features, it adds additional dice. When the dice are clicked, the rightmost dice sends 1d20, the second 2d20, and so on. The bonuses make no sense to be rolled like this and as such I believe the entire dice icon to be injected in error. I check on the file dndbeyond_character.js and I believe the issue to be on line 5060 
`
if (paneClass == "ct-sidebar__pane-controls" || paneClass == "ct-beyond20-settings-pane") {
                continue;
}
`
I believe this needs to include the 'ct-class-feature-pane' however I am not in a situation where coding this is viable so I am leaving the fixing of the issue to you.

**Comment by kakaroto** [comment] 2020-05-08 03:51
Thanks for the report and attempt at investigating the cause.
It's a duplicate of #183 and has already been fixed in the dev version.

**Closed by kakaroto** 2020-05-08 03:51 UTC
Labels: duplicate
