### ISSUE TITLE
Positive dice modifiers are added incorrectly in roll20

### ISSUE THREAD

**Issue by Inkemann** [kakaroto/Beyond20#636] opened 2020-12-21 23:34 UTC
When a positive dice modifier is set in Beyond20 (for example +d4 for Bless/Guidance), the roll in roll20 will always be a 0, as it results in a ++d4 (instead of just +d4) which roll20 doesn't understand.

**To Reproduce**
Roll a check with a positive dice modifier from DnDBeyond while in a roll20-Room.

**Expected behavior**
The dice modifier should be added to the original roll.

**Comment by DarrynGlass** [comment] 2020-12-22 00:55
As a note, adding 0 into the custom roll dice formula bonus is a quick workaround to make it work.

![image](https://user-images.githubusercontent.com/29684482/102836092-1465df80-43be-11eb-9b2c-aff52a1869e8.png)

**Comment by kakaroto** [comment] 2020-12-22 05:39
Thanks. Closing as duplicate of #614

**Closed by kakaroto** 2020-12-22 05:39 UTC
Labels: bug
