### ISSUE TITLE
Extra information with the to-hit and damage dice not splitting

### ISSUE THREAD

**Issue by HaarisQureshi** [kakaroto/Beyond20#433] opened 2020-07-08 10:49 UTC
Saw the bit in the Known Issues about 'Cannot separate to-hit and damage dice (disabled “auto roll damages” option) when using the Digital Dice.' - Tried to find if there was already an issue opened here about it add to but couldn't so apologies if there is, but just in case this is helpful and you weren't aware - when I tested it out, I noticed that when I did disable the auto-roll feature, after rolling (and it rolling both), I looked back at the settings and the auto-roll had toggled itself back on despite being saved as off.

**Comment by kakaroto** [comment] 2020-07-08 18:15
Yep, it reverts it back to enabled on purpose because it was the easiest way to make it work without breaking the whole thing apart :p
The known issue isn't because it's a bug, but it's because it's something that I have no idea how to achieve (i.e: the "roll damages" button on the VTT would need to send back a message to the D&D Beyond page to tell it to roll the damages back with the digital dice, etc.. usually the roll damages buttons are linked to a local function, but this time the function that it needs to link to is on another tab, so it can't call it.. anyways, it's complicated, lol

**Comment by HaarisQureshi** [comment] 2020-07-09 14:32
Ahh okay,

**Comment by kakaroto** [comment] 2020-07-11 19:16
Closing this btw as it's duplicate of #307

**Closed by kakaroto** 2020-07-11 19:16 UTC
