### ISSUE TITLE
Beyond20 Dice Rolls not showing & Purple Boxes in chat

### ISSUE THREAD

**Issue by KayleePup** [kakaroto/Beyond20#783] opened 2021-04-23 18:29 UTC
As we are playing our D&D game in Roll20 last night we noticed that the rolls show up in the chat in purple boxes and do not show the calculations (we do see we can hover over them) but prefer the other way.

The 3D dice are also no longer rolling on the screen in Roll20.  We can turn them on in D&D Beyond and see them there but we prefer for everyone to see the rolls.

This happens on Firefox & Chrome, latest updates applied.

**Comment by Aeristoka** [comment] 2021-04-23 18:30
Duplicate of #765

**Closed by Aeristoka** 2021-04-23 18:30 UTC
Labels: bug
