### ISSUE TITLE
Selected template no longer works

### ISSUE THREAD

**Issue by halovx** [kakaroto/Beyond20#595] opened 2020-12-03 20:35 UTC
**Describe the bug**
When rolling from DnDBeyond, the rolls appear under the default template as opposed to the selected one.

**Expected behavior**
![image](https://user-images.githubusercontent.com/75450837/101085080-ce7bdf80-35a6-11eb-9dfb-00a52406fc9e.png)
![image](https://user-images.githubusercontent.com/75450837/101085088-d471c080-35a6-11eb-85a6-1bb563df578b.png)

**Screenshots**
However now a roll appears like this:
![image](https://user-images.githubusercontent.com/75450837/101085180-fb2ff700-35a6-11eb-8cb7-8b5c6846b6af.png)

**Comment by Aeristoka** [comment] 2020-12-03 20:53
Duplicate of #594 and #593 

This is fixed in the Dev version (https://github.com/kakaroto/Beyond20#developer-mode-installation), use that if you want an immediate fix, or join the Discord: https://discord.gg/ZAasSVS and check #announcements channel for a workaround

@kakaroto please close

**Closed** 2020-12-05 22:51 UTC
Labels: bug
