### ISSUE TITLE
Can't get rolls to display in Roll20 Format in Roll 20

### ISSUE THREAD

**Issue by whokan** [kakaroto/Beyond20#607] opened 2020-12-06 18:33 UTC
**Describe the bug**
I am trying to get my rolls in Roll 20 to display in the Roll 20 format.

I have the "Use D&D Beyond's Digital Dice" toggle disabled. I have selected D&D 5E by Roll 20 as the renderer. But the rolls display in the Beyond DND format like the screenshot below. I have tried toggling the settings, closing and reclosing the tabs, and restarting chrome and can't get the expected format to display.

![image](https://user-images.githubusercontent.com/18322902/101288861-b0340080-37ad-11eb-829a-9740b6697749.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/18322902/101288888-d22d8300-37ad-11eb-935e-ea209df0f2fb.png)

**Expected behavior**
I hope to get this format to display

![image](https://user-images.githubusercontent.com/18322902/101288897-e70a1680-37ad-11eb-9709-11ddb66da6b1.png)

**Browser Info (please complete the following information):**
 - Chrome 
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
Thank you :)

**Comment by Nyx-WildSiren** [comment] 2020-12-06 18:35
You just need to download the dev version from here on github

**Comment by DarrynGlass** [comment] 2020-12-06 18:37
This is a duplicate of multiple other issues raised.   Roll 20 made an update that broke things. See https://github.com/kakaroto/Beyond20/issues/592

Or read this post from discord about installing the dev version where this has been fixed https://discordapp.com/channels/578874022968688640/697853409700610158/783518857171042394

@kakaroto please close

**Closed** 2020-12-06 19:48 UTC
Labels: bug
