### ISSUE TITLE
Sync D&D Beyond Combat Tracker with FoundryVTT

### ISSUE THREAD

**Issue by Puddinglord** [kakaroto/Beyond20#641] opened 2020-12-25 16:16 UTC
**Is your feature request related to a problem? Please describe.**
There is currently an option to sync the D&D Beyond encounter tracker with Roll20's combat tracker and overwrite the Roll20 tracker. I would love it if Foundry got this ability as well.

**Describe the solution you'd like**
I would love it if I could use the D&D Beyond combat tracker instead of Foundry's built-in one and have it sync with the state of D&D Beyond's tracker. This feature would behave similarly to the setting for Roll20's combat tracker.

**Comment by Aeristoka** [comment] 2021-05-06 20:16
Closing as duplicate of #554

**Closed by Aeristoka** 2021-05-06 20:16 UTC
Labels: enhancement
