### ISSUE TITLE
Way of the Sun Soul Monks Radiant Sun Bolt displays wrong text

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#733] opened 2021-03-29 01:57 UTC
**Describe the bug**
Way of the Sun Soul Monks level 3 Ki ability displays the wrong text when clicking the Beyond 20 button.

**To Reproduce**
https://www.dndbeyond.com/characters/47493227
Click on Features and Traits.
Find Radiant Sun bolt
Click on Beyond 20 button
![image](https://user-images.githubusercontent.com/29684482/112777482-f684c800-9007-11eb-9eb2-1973aa395c3b.png)

**Expected behavior**
Display the text for Radiant Sun Bolt

**Screenshots**
Displays Armor calculation instead
![image](https://user-images.githubusercontent.com/29684482/112777528-1ae0a480-9008-11eb-84e0-684e5ed86243.png)

**Browser Info (please complete the following information):**
 - Chrome

**Comment by Aeristoka** [comment] 2021-03-29 01:59
Duplicate of #718

**Comment by DarrynGlass** [comment] 2021-03-29 02:01
Thx

**Closed** 2021-03-29 02:01 UTC
Labels: bug

**Comment by Aeristoka** [comment] 2021-03-29 02:08
No problem, this one is weird as it's not ALL characters that I've seen, just some (or some classes?). Appreciate the report!
