### ISSUE TITLE
Cantrip doesn't roll for Hit if cast from Action list

### ISSUE THREAD

**Issue by Ryuichiro** [kakaroto/Beyond20#439] opened 2020-07-08 22:53 UTC
Tested with *Thorn Whip* cantrip.

- When cast from Spell list it rolls for hit and damage
![chrome_08_224846819](https://user-images.githubusercontent.com/4333206/86978155-af9b2d80-c16d-11ea-8816-d857a1eae206.png)
![image](https://user-images.githubusercontent.com/4333206/86978173-ba55c280-c16d-11ea-8d28-8a15642cd115.png)

- When cast from Action list it only rolls for damage.
![chrome_08_224857381](https://user-images.githubusercontent.com/4333206/86978114-9b573080-c16d-11ea-9747-d809326817b2.png)

**Comment by Aeristoka** [comment] 2020-07-08 23:10
Duplicate of #435 and #438 

Fixed in the Dev version

**Comment by Aeristoka** [comment] 2020-07-08 23:28
@kakaroto please close

**Closed** 2020-07-08 23:55 UTC
