### ISSUE TITLE
strange idle processor load

### ISSUE THREAD

**Issue by gajustempus** [kakaroto/Beyond20#1106] opened 2024-04-04 08:23 UTC
Running on Chrome 123.0.6312.88 on Win11 Professional, most recent updates installed, I experienced a strange high idle processor load (only noticed because my CPU fan suddenly toured up out of the blue) - Beyond20 was using 4 of my 24 processor cores at 100% without being used in any kind.

I've been browsing the normal internet. No dndbeyond, no Roll20 or anything like that open, nor did I open any of these pages the last couple of days.

Beyond20 was the only Chrome process eating up performance. Ending it in Task Manager prompted a "Beyond20 has crashed". That's how I could identify the process.

**Comment by kakaroto** [comment] 2024-04-04 21:32
Hi,
I don't see how that could happen, there's nothing that should take 100% cpu in the extension, especially not if you don't have a ddb/roll20 page open. I checked the extension's background script and it doesn't have any loops that could cause this behavior either.
I'm also surprised about the "4 out of 24 processor cores" since javascript is single threaded, so the maximum it could do, even if there was an infinite loop somewhere, would be taking up one cpu, not 4.
Is this issue reproducible for you? If yes, can you inspect the background script and screenshot the console log?
From the 'manage extensions' page, click the "inspect view background page" link, then screenshot what you see in the console tab of the new devtools window (if there's anything sensitive information in there, make sure to review it and censor it out, before posting).
![image](https://github.com/kakaroto/Beyond20/assets/27990/1787295b-8476-4d35-9efc-572f85e7440d)

**Comment by Aeristoka** [comment] 2024-04-04 22:01
Did you install Beyond20 from ANYWHERE but the Chrome/Firefox stores?

**Comment by kakaroto** [comment] 2024-04-04 23:28
> Did you install Beyond20 from ANYWHERE but the Chrome/Firefox stores?

That is a good point! 
Can you provide us with the extension ID (as shown in my previous screenshot) and its version as well?

**Comment by gajustempus** [comment] 2024-04-05 08:01
To begin with: No, I only use software from the according browser's original stores. I don't want to go catch malware in my browser to fetch my banking details. You can't be 100% sure by doing to, but the odds are WAY lower to get infected that way. So that's my way-to-go.

Second: Just for reference and to answer potential other questions - the system wasn't old or filled with crap. It was a fresh install of Win11, only about two weeks old, with just Chrome, Brave, Vivaldi, Office, Blender and Cura installed on it.

And third: Sorry, I can't go into the Dev tools window anymore, as my first step of dealing with the issue after noticing it was this part of software causing my CPU fan to go wild on me (had been the first time in these two weeks btw. - that's why I noticed) was to remove it from my system. Neither do I want to be annoyed by my CPU fan all the time for no particular reason, nor do I want to raise my electricity bill without any good reason either. And Intel isn't known for low power comsumption CPUs anymore.

I can give you all the other input you might need to look into the matter, but I don't have the software on my system anymore right now.

**Comment by kakaroto** [comment] 2024-04-05 21:30
> I can give you all the other input you might need to look into the matter, but I don't have the software on my system anymore right now.

Please provide any information you may have that could help us reproduce the problem. Unfortunately, without any way of reproducing it or seeing logs that might indicate a cause, there's really not much we can do.
Considering this is the first time I hear of something like this, and we have half a million users, I'm leaning towards this being specific to your setup, rather than a bug in the extension, but I'd love for you to prove me wrong so we can fix it.
If you can re-enable the extension to see if you get the same behavior or not, that can help, but if you don't want to re-enable it, I'd understand.

**Comment by kakaroto** [comment] 2024-04-25 03:32
Closing issue as it's non-reproducible and we haven't received additional information from the user.
If you do try again and have additional information to help us figure out what happened here, feel free to re-open the issue with the new info.

**Closed by kakaroto** 2024-04-25 03:32 UTC
Labels: bug
