### ISSUE TITLE
Clicking on spells rolls the cast instead of opening the info

### ISSUE THREAD

**Issue by JoshSmithCode** [kakaroto/Beyond20#1146] opened 2024-07-12 10:35 UTC
**Describe the bug**
Previously when clicking on the spell name the spell description would be toggled open, now when clicking on it, the spell is cast instead. 

**To Reproduce**
1. Go to character sheet spell tab
2. Click on a spell name
3. See the spell cast and the spell description not open

**Expected behavior**
Normally clicking on the spell name causes the info panel to open and does not cast the spell

**Browser Info (please complete the following information):**
 - Chrome
 - Version 126.0.6478.127
 - ![image](https://github.com/user-attachments/assets/76f430e6-833c-43b3-923d-f54e675e7d5a)

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by smnc** [comment] 2024-07-13 01:39
Likely tied to #1145

**Comment by ballra** [comment] 2024-07-14 19:09
Adding to issue 1146.  In addition to bugs described in here and #1145 , unarmed strike attack rolls are not rolling or transferring over to Roll20. Standard attacks (light crossbow, guiding bolt) transfer over.  Magical /homebrew weapons attack rolls do not roll and post the item description to Roll20 chat. Skill checks roll the check and a second d20. 

Google Chrome Version 126.0.6478.127
and Firefox release 128.0

**Comment by dmportella** [comment] 2024-07-15 15:30
> Adding to issue 1146. In addition to bugs described in here and #1145 , unarmed strike attack rolls are not rolling or transferring over to Roll20. Standard attacks (light crossbow, guiding bolt) transfer over. Magical /homebrew weapons attack rolls do not roll and post the item description to Roll20 chat. Skill checks roll the check and a second d20.
> 
> Google Chrome Version 126.0.6478.127 and Firefox release 128.0

I made the fixes for that on the pull request

**Comment by kakaroto** [comment] 2024-07-26 09:29
My understanding of this issue is that when you click on a spell name in the sheet, Beyond20 rolls it instead of not doing anything and letting DDB site open the side panel?
That's very weird, but also, I'm unable to reproduce it. I wonder if it's related to the DDB website changes they did recently, though I did test with the public release and still can't reproduce it.
I plan on releasing an update soon, if you get the issue with the newer release (or if I misunderstood the actual issue), please let us know.
Thanks

**Comment by kakaroto** [comment] 2024-09-23 02:40
I believe this was fixed in the last release, so closing the issue.
Feel free to reopen it if I misunderstood the problem.

**Closed by kakaroto** 2024-09-23 02:40 UTC
Labels: bug
