### ISSUE TITLE
Charged Items

### ISSUE THREAD

**Issue by filmadept** [kakaroto/Beyond20#474] opened 2020-07-27 15:02 UTC
When attempting to use a charged item (such as a staff) to cast a spell, I've run into an issue when the item allows multiple charges to be used to upcast a spell (as an example, Moonbeam. The item allows 2 charges for a 2nd level Moonbeam, up to 5 charges for a 5th level Moonbeam).

When I adjust the spell level on the cast page (with the +/- buttons), the number of charges correctly increases, but when I click the cast button, what happens is that the spell is cast /5/ times in roll 20 at the level I requests.  

ie: 
2 charges, 5 casts of 2nd level moonbeam
3 charges, 5 casts of 3rd level moonbeam, etc

**Comment by Aeristoka** [comment] 2020-07-27 15:07
Duplicate of #459

**Closed** 2020-07-27 22:12 UTC
Labels: duplicate
