### ISSUE TITLE
Monk's hands of healing rolls d20 instead of d6

### ISSUE THREAD

**Issue by sunrize531** [kakaroto/Beyond20#706] opened 2021-03-08 09:38 UTC
**Describe the bug**
Rolls d20 instead of martial arts die when rolling monk abilities from the skill's description.

**To Reproduce**
1. Go to 'Character sheet'
2. Click on B icon next to hand's of healing description, 2nd one that supposed to roll with modifier (deflect missiles works the same)'
3. Rolls d20+Wis instead of martial arts die +Wis.
4. If clicked on the first B icon - rolls martial die but without wis mod.

**Expected behavior**
Should roll  correct die.

**Screenshots**
![image](https://user-images.githubusercontent.com/774797/110302994-c8f0c400-7ff1-11eb-9bfa-1e21aad966c4.png)

**Browser Info (please complete the following information):**
 - Browser: chrome
 - Version: 88.0.4324.190

**Comment by Aeristoka** [comment] 2021-03-08 14:03
Duplicate of #531 
@kakaroto will need to work out how to capture those together, as DnDBeyond changed the underlying formatting so they capture separately.

**Comment by kakaroto** [comment] 2021-03-17 10:53
Yeah, that's a complicated one to fix, slated for the 2.4.0 release. Closing as duplicate.

**Closed by kakaroto** 2021-03-17 10:53 UTC
Labels: bug, duplicate
