### ISSUE TITLE
Advantage plus custom roll adds custom roll twice

### ISSUE THREAD

**Issue by cmbarona** [kakaroto/Beyond20#962] opened 2022-03-20 15:39 UTC
**Describe the bug**
I set up a custom roll to account for Superiority Dice: +1d8. When I apply this to a roll with advantage, it rolls the extra d8 twice.

**To Reproduce**
1. Open the Beyond20 Hotkey Manager
2. Add New Hotkey: Override Global Settings: Custom Modifier: Custom Formula = 1d8
3. Activate the new hotkey in tandem with any Advantage or Disadvantage hotkey
4. Activate any applicable roll

**Expected behavior**
The roll would be made with advantage, but the custom dice would only be rolled once and its result applied equally to both Advantage rolls. In other words,
Expected: {(Advantage Roll 1 + Ability + Proficiency) + (Custom Roll 1)} ; {(Advantage Roll 2 + Ability+ Proficiency) + (Custom Roll 1)}
Actual: {Advantage Roll 1 + Ability+ Proficiency + Custom Roll 1} ; {Advantage Roll 2 + Ability+ Proficiency + Custom Roll 2}

**Screenshots**
![image](https://user-images.githubusercontent.com/101484946/159170238-6f5f11fa-e044-42e6-87ae-848754f225d8.png)
![image](https://user-images.githubusercontent.com/101484946/159170255-1de2440b-2a35-469a-955e-fc2d8b079f57.png)

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by Aeristoka** [comment] 2022-03-20 18:57
This is directly related to how rolls are processed by Beyond20, and very explicitly when rolls are sent to be processed by FoundryVTT/Astral/Roll20, we have no way to process something like this on that end, as the roll results are just posted, so this is going to be the behavior, unless @kakaroto has some other input on it.

**Comment by Aeristoka** [comment] 2022-03-26 23:22
Confirmed Duplicate of #642 

See https://github.com/kakaroto/Beyond20/issues/642#issuecomment-1001073349 in particular.

**Comment by kakaroto** [comment] 2022-03-26 23:22
As @Aeristoka pointed out, it's just not something that we can do for technical reasons. This is a duplicate of https://github.com/kakaroto/Beyond20/issues/642 in which I replied with more details.
The short answer is "either way, it's random"

**Closed by Aeristoka** 2022-03-26 23:22 UTC
Labels: unsure
