### ISSUE TITLE
Character not syncing between D&D Beyond and Roll20

### ISSUE THREAD

**Issue by Tamarack928** [kakaroto/Beyond20#177] opened 2020-04-09 16:21 UTC
I can use the app to roll from D&D beyond into Roll20 for things like skill checks but not attacks or spells like Eldritch Blast.  The option simply is not there to roll for these.  Additionally when I do roll a skillcheck it won't sync with the character therefore the character name comes up as "Null". 

When looking at errors I see, "uncaught typeerror: cannot read property 'firstchild' of undefined

thoughts?

**Comment by Aeristoka** [comment] 2020-04-09 16:22
https://github.com/kakaroto/Beyond20#developer-mode-installation

You likely have been upgraded to the Alpha character sheet on DnDBeyond. Try installing the Developer version of the extension (and disable the store version on Chrome/Firefox). Try it again with that.

**Comment by kakaroto** [comment] 2020-04-09 16:23
Duplicate of #174 #175 and #176

**Closed by kakaroto** 2020-04-09 16:23 UTC
Labels: duplicate

**Comment by Tamarack928** [comment] 2020-04-09 17:01
This fixed the issue Aeristoka.  Thank you so very much!
