### ISSUE TITLE
Digital Dice Target - Asked Every Time Instead of Using the Default Game Log Selection

### ISSUE THREAD

**Issue by amenokos** [kakaroto/Beyond20#812] opened 2021-06-04 03:34 UTC
**Describe the bug**
When Beyond20 is configured to use D&D Beyond's Digital Dice, it's necessary to click a secondary ROLL button near the custom dice roller (bottom left) before the dice are rolled and values are sent to the VTT. 

**To Reproduce**
1. Make sure _Use D&D Beyond's Digital Dice_ is enabled in Beyond20's settings.
2. Click a rollable area on your DDB character sheet (attack, damage, or combo-attack/damage).
3. See that a ROLL button appears in the lower-left (near the custom dice roller) that indicates the Dice Target (Self or Everyone).
4. Click that ROLL button in the lower-left, and see that the digital dice are rolled, followed by the values being sent to the VTT.

Notes: If the Beyond20 extension is disabled, the DDB character sheet rolls the digital dice immediately when you click a rollable area on the character sheet. If the _Use D&D Beyond's Digital Dice_ is disabled in Beyond20's settings, the dice values are sent directly to the VTT without the need to click a secondary ROLL button.

**Expected behavior**
DDB's Game Log allows you to set the default Dice Target. When clicking a rollable area on your DDB character sheet, the digital dice should be rolled immediately with the values being sent to the VTT without having to click a secondary ROLL button in the lower-left when the default dice target is already selected in DDB's Game Log. I played earlier this evening, and it became quite tedious having to click twice every time I rolled dice.

**Screenshots**
![image](https://user-images.githubusercontent.com/69495414/120741196-9ce6c100-c4c2-11eb-8755-ad98e439fa0b.png)

![image](https://user-images.githubusercontent.com/69495414/120741272-c3a4f780-c4c2-11eb-9670-ec5450dc1c40.png)

![image](https://user-images.githubusercontent.com/69495414/120741287-cbfd3280-c4c2-11eb-952a-232140ce58fc.png)

**Browser Info (please complete the following information):**
 - Chrome Version 90.0.4430.218 (Official Build) (64-bit)
 - Beyond 20 - Release Version 2.4.3

**Comment by kakaroto** [comment] 2021-06-04 04:22
Thanks for the report. This was due to yesterday update of the D&D Beyond website (just after my own Beyond20 release!)
Closing as duplicate of #805 which is already fixed in the dev version.

**Closed by kakaroto** 2021-06-04 04:22 UTC
Labels: bug

**Comment by amenokos** [comment] 2021-06-04 04:46
Thank you. I attempted to search through the issue list to see if someone already posted this problem. Looks like I missed it. LOL

**Comment by kakaroto** [comment] 2021-06-04 05:29
Thanks for trying! You probably missed it cause it was already closed :)
