### ISSUE TITLE
Rolling an attack opens the weapon description popup

### ISSUE THREAD

**Issue by phookade** [kakaroto/Beyond20#1184] opened 2024-10-30 14:24 UTC
**Describe the bug**
You roll an attack. The weapon description popup opens up.

**To Reproduce**
1. Disable "D&D Beond's Digital Dice"
2. roll an attack
3. The weapon description popup opens and stays open.

**Expected behavior**
It should simply roll the attack and transmit the result to the VTT.

**Browser Info (please complete the following information):**
 - Browser firefox
 - Version 132.0

**Additional context**

**Comment by dmportella** [comment] 2024-10-30 14:40
@phookade what version of the extension have you got?

**Comment by phookade** [comment] 2024-10-30 15:38
2.9.8

**Comment by kakaroto** [comment] 2024-10-30 18:32
The side panel is what Beyond20 needs and uses in order to understand what roll to make. It is required and will always open when you click on a roll button. It also opens automatically by D&D Beyond whenever you click on an attack, skill, etc... that's just the normal way the character sheet works. You can try it with the extension disabled too, it will behave the same way.
If you have digital dice enabled, the dice when rolling will close the side panel, and that's again normal D&D Beyond behavior. Beyond20 has nothing to do with it.
Closing this as an invalid "bug", since it's the expected behavior and I have no plans (or reason) to change that behavior.

**Closed by kakaroto** 2024-10-30 18:32 UTC
Labels: invalid
