### ISSUE TITLE
Roll20 Hot Keys not replacing asking for roll each time

### ISSUE THREAD

**Issue by ghost** [kakaroto/Beyond20#620] opened 2020-12-09 19:47 UTC
Despite setting up hot keys in Roll20, rolls are only being executed based on previously selected type of roll in settings. I.E. any hot key used for a roll only produces the type of roll set in settings.

**Comment by Aeristoka** [comment] 2021-05-06 20:04
Can you be more specific here? I'm not at all sure what you mean.

**Comment by kakaroto** [comment] 2021-06-01 01:39
Closing this as it's very unclear what the issue is, and we haven't received any new information.
Feel free to re-open the issue with more information and steps to reproduce the bug you seem to encounter.

**Closed by kakaroto** 2021-06-01 01:39 UTC
Labels: bug
