### ISSUE TITLE
Beyond20 rolls from character sheet not reaching FoundryVTT

### ISSUE THREAD

**Issue by HarmAssassin** [kakaroto/Beyond20#1141] opened 2024-06-24 17:01 UTC
I'm using Windows 11 (fully updated), Chrome (fully updated), the Beyond20 chrome extension, FoundryVTT v.12.327, Beyond20 companion module (1.5.2) as well as the DDB-Beyond Importer and D&D Beyond Gamelog, (and more).

Up until the FoundryVTT 12.327 update, the Beyond20 extension worked perfectly.

After that update character sheets on D&D Beyond only send damage rolls and custom rolls to FoundryVTT. All other rolls do not seem to transfer to Foundry.

I've uninstalled/reinstalled the Beyond20 extension. I've ensured that all modules in Foundry (and Foundry) are up to date. I've tried character sheets set to Public or Private, in and out of the DnDBeyond Campaign. I've verified that the character sheet unique ID # is assigned and mapped to the player and character sheets in Foundry as well as mapped in the D&D Beyond Gamelog core settings.

I've also tried uninstalling D&D Beyong Gamelog (as I know it sometimes doesn't play nice with Beyond20) - same result.

Still, only damage rolls and custom rolls are sent to Foundry (regardless of whether the sheet is set to public or private, in or out of the campaign).

**Comment by kakaroto** [comment] 2024-06-25 06:03
Looks like a duplicate of https://github.com/kakaroto/Beyond20/issues/1127

**Closed by kakaroto** 2024-06-25 06:03 UTC
Labels: bug
