### ISSUE TITLE
Rolling for spell attack to hit rolls for damage instead

### ISSUE THREAD

**Issue by ya-hs** [kakaroto/Beyond20#438] opened 2020-07-08 21:11 UTC
I saw under known features that it says "Some spells and weapon attacks are not rolling their “To hit” dice as expected" but wasn't entirely sure if it was the issue I'm having. For myself, no matter which character sheet I'm on for my players, the spells only roll damage when on the "Actions" tab on D&DB.

When using the D&DB "Spells" page, it works as intended. I've had no issues with weapon attacks thus far.

**Comment by kakaroto** [comment] 2020-07-08 21:15
Yeah, that's the known issue, which was fixed. Closing as duplicate of #435

**Closed by kakaroto** 2020-07-08 21:15 UTC
