### ISSUE TITLE
Some spells and weapon attacks are not rolling their “To hit” dice as expected - Info

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#440] opened 2020-07-09 00:44 UTC
I was testing this and discovered that if you cast a spell from the Spells tab it correctly rolls the To Hit (at least for the spells I tested).  It only fails to roll this from the Actions tab.

I could not find an issue for this in the list, but wanted to share this in case it was not known.

**Comment by Aeristoka** [comment] 2020-07-09 00:47
Duplicate of #439 and #438 and #435 .

@kakaroto please close

**Closed** 2020-07-09 00:47 UTC
