### ISSUE TITLE
Rolling in DDB with Advantage/Disadvantage shows an unparsable notification

### ISSUE THREAD

**Issue by jakebiesinger** [kakaroto/Beyond20#695] opened 2021-02-18 05:24 UTC
**Describe the bug**
Advantage and Disadvantage are not handled correctly by Astral Tabletop, showing a weirdly formatted table with a single roll that always shows the value `0`.

**To Reproduce**
1. Start a game in Astral, connect Beyond20 to dndbeyond
2. Right-click on a roll button and choose either "advantage" or "disadvantage", e.g.,
![image](https://user-images.githubusercontent.com/463861/108308247-aeeb6080-716c-11eb-9b64-c0bb9e57ab03.png)
3. Observe the results of the roll in Astral

**Expected behavior**
I expect to see two rolls shown in Astral in a nicely formatted table, representing advantage / disadvantage.

**Screenshots**
![image](https://user-images.githubusercontent.com/463861/108308956-e575ab00-716d-11eb-9a12-fa9335b77d4a.png)
![image](https://user-images.githubusercontent.com/463861/108308938-dbec4300-716d-11eb-9497-305beaf7e0a8.png)

**Browser Info (please complete the following information):**
 - Browser: Chrome on Mac
 - Version 88
 - No dev console errors

**Additional context**

**Comment by Aeristoka** [comment] 2021-02-18 05:28
@adriangaro this seems like it's up your alley.

**Comment by jakebiesinger** [comment] 2021-02-18 06:18
Here's the console output from dndbeyond when I roll with advantage + disadvantage

[www.dndbeyond.com-1613629027826.log](https://github.com/kakaroto/Beyond20/files/6000618/www.dndbeyond.com-1613629027826.log)
[www.dndbeyond.com-1613629037785.log](https://github.com/kakaroto/Beyond20/files/6000620/www.dndbeyond.com-1613629037785.log)
[www.dndbeyond.com-1613629054613.log](https://github.com/kakaroto/Beyond20/files/6000621/www.dndbeyond.com-1613629054613.log)
[www.dndbeyond.com-1613629059415.log](https://github.com/kakaroto/Beyond20/files/6000622/www.dndbeyond.com-1613629059415.log)

**Comment by adriangaro** [comment] 2021-02-18 09:44
I have tried reproducing this error as I was notified of it previously. Maybe with the logs here I'll be able to find what causes it. thanks! Will take a look

**Comment by jakebiesinger** [comment] 2021-02-18 19:52
@adriangaro this happens for all my character sheets. LMK if you need a live demo or whatever to track this down.

**Comment by adriangaro** [comment] 2021-02-21 11:59
Is this beta or the normal version of Astral?

**Comment by kakaroto** [comment] 2021-02-24 05:53
Those buttons in the right click menu are from D&D Beyond and that's D&D Beyond doing the rolls. Beyond20 in that case is only transferring over the result of the digital dice roll that DNDB did, just like if you did a custom roll.
To use Beyond20 specifically, you would click the Beyond20 icon while holding Shift for advantage or Control for disadvantage.
It doesn't seem to be specific to Astral though because I also got a `NaN` result in Foundry. The problem is with parsing the results. I noticed that it says "1d20" even though it rolls 2d20, same for damage with critical hit. It shows correctly in the game log though, and I've reported the issue to the D&D Beyond team.

I'll need to fix this from the dndb parsing side.

**Closed** 2021-04-16 09:06 UTC
Labels: bug
