### ISSUE TITLE
Error when clicking a weapon attack

### ISSUE THREAD

**Issue by phillipchengh** [kakaroto/Beyond20#430] opened 2020-07-08 03:55 UTC
I noticed this error gets logged when I'm clicking on a weapon attack, so the message doesn't get sent on roll20. Let me know if I can help with anything else.

dndbeyond_character.js:4133 Uncaught TypeError: Cannot read property 'Ranger' of null
    at Character.hasClass (dndbeyond_character.js:4133)
    at rollItem (dndbeyond_character.js:4367)
    at execute (dndbeyond_character.js:5050)
    at dndbeyond_character.js:5139
    at HTMLButtonElement.<anonymous> (dndbeyond_character.js:3058)
    at HTMLButtonElement.dispatch (jquery-3.4.1.min.js:2)
    at HTMLButtonElement.v.handle (jquery-3.4.1.min.js:2)

**Comment by shadow7412** [comment] 2020-07-08 04:02
Is this reproducible using the development version of Beyond 20?

**Comment by kakaroto** [comment] 2020-07-08 04:04
This is a duplicate of #427 which has been fixed in the dev version.

**Closed by kakaroto** 2020-07-08 04:04 UTC
Labels: duplicate
