### ISSUE TITLE
Twilight Sanctuary dice roll broken

### ISSUE THREAD

**Issue by heizusan** [kakaroto/Beyond20#598] opened 2020-12-04 02:48 UTC
Twilight Sanctuary (Twilight Cleric's channel divinity from "Tasha's") should roll 1d6 + cleric level. But, it splits the die roll from the bonus, with two separate beyond20 interactions.

Clicking on the 1d6 rolls 1d6 + 0 (I believe - the text in the macro is strange: {{Channel Divinity: Twilight Sanctuary(1d6)={[[ 1 + 1d0cs>1cf>0 [1d6] = (1)]]}}}).

Clicking on the + # rolls 1d20 + cleric level (The macro uses the number, directly).

There should be one clickable element, which rolls 1d6 + cleric level.

**Comment by Aeristoka** [comment] 2020-12-04 03:23
Duplicate of #583

**Closed** 2020-12-08 02:38 UTC
