### ISSUE TITLE
Flame Tongue Rapier does not roll attack, just damage, in Roll20

### ISSUE THREAD

**Issue by stuartlangridge** [kakaroto/Beyond20#443] opened 2020-07-09 22:42 UTC
I have a _flame tongue rapier_. Clicking it in the Actions tab shows the sidebar and clicking the Beyond20 button rolls its damage in Roll20 but _not_ an attack roll, like this:

![image](https://user-images.githubusercontent.com/4356350/87097746-c741e700-c23d-11ea-9245-2c10f04ecc24.png)

Is this something wrong with my setup? It may be related to the recent changes to DDB's sheet?

**Comment by kakaroto** [comment] 2020-07-09 22:44
Duplicate of #439 and #438 and #435 and #440.

Expect an update soon with the fix.

**Closed by kakaroto** 2020-07-09 22:44 UTC
