### ISSUE TITLE
Luckstone + Death Save = no bonus

### ISSUE THREAD

**Issue by tony--** [kakaroto/Beyond20#612] opened 2020-12-08 05:30 UTC
**Describe the bug**
Luckstone: While this polished agate is on your person, you gain a +1 bonus to ability checks and saving throws.
Rolling a death save with an attuned Luckstone equipped, no bonus is applied.

**To Reproduce**
1. Equip and attune a Luckstone (Stone of Good Luck)
2. Roll a death save with Beyond 20
3. Notice that no bonus is applied

**Expected behavior**
With an attuned Luckstone equipped, a +1 bonus is applied to death saves.

**Comment by Aeristoka** [comment] 2020-12-08 06:14
Duplicate of #163

**Comment by kakaroto** [comment] 2020-12-08 16:29
Oh good catch, it is a duplicate, thx! closing 👍

**Closed by kakaroto** 2020-12-08 16:29 UTC
Labels: bug

**Comment by tony--** [comment] 2020-12-15 21:14
FWIW I searched for luckstone and stone of good luck but did not think to search for Death Saves, thanks @Aeristoka
