### ISSUE TITLE
Switching back and forth between dice hangup

### ISSUE THREAD

**Issue by Brazedowl** [kakaroto/Beyond20#349] opened 2020-06-03 14:04 UTC
Somehow stuck with it rolling dndbeyond dice on dndbeyond only. I tried hard to recreate it and put the actual steps I clicked things in.

Starting Condition: dndbeyond dice off (to make it work for the previous update) - Worked

Change 1: Turned on dndbeyond dice, and turned on the toggle in the beyond 20 settings. Worked and sent it to roll 20 correctly. But the way it displays is not formatted as pretty and does not show the character that made the roll. Picture below shows the non-dndbeyond dice roll vs the with-dndbeyond dice roll.

![Annotation 2020-06-03 094841](https://user-images.githubusercontent.com/56116837/83645455-8391f880-a580-11ea-8621-c4dd9ad6b224.jpg)

Change 2:  Turned off "use dndbeyond dice" --> works and happily sends to roll20

Change 3: Turned off both the actual dndbeyond dice toggle AND the "use dndbeyond dice" beyond 20 toggle. Then turned them back on. It should at this point roll dndbeyond digital dice, and send the result to roll20. Alas, it just rolls on dndbeyond and shows the result there only. Picture below:

![Annotation 2020-06-03 094841](https://user-images.githubusercontent.com/56116837/83646285-71648a00-a581-11ea-9db8-7cfce6eb4805.jpg)

Refreshing the page returns it to its default state and allows the process to be done again.

**Comment by Aeristoka** [comment] 2020-06-03 14:07
Not showing the name on the "less pretty" rolls is a known issue.

You get to pick the pretty Roll20 display OR Digital Dice on DnDBeyond, due to how the rolls have to be processed.

Duplicate of #342 and #346

**Comment by kakaroto** [comment] 2020-06-04 02:22
There might be an issue that when enabling/disabling the digital dice in DNDB, it clear outs my own click handlers on that area. Do you still see the B20 tooltip icon when you hover on the skill? And if you click somewhere to change the content of the page (like selecting a skill so it opens the sidebar) does that seem to fix it ?

**Comment by Aeristoka** [comment] 2021-05-06 20:32
@Brazedowl I believe this has been fixed incidentally now, can you verify?

**Comment by kakaroto** [comment] 2021-05-29 05:32
I think it has. Closing for now. @Brazedowl feel free to re-open the issue if you still encounter it.
Thanks.

**Closed by kakaroto** 2021-05-29 05:32 UTC
Labels: bug
