### ISSUE TITLE
Conditional advantage/disadvantage enabled by default

### ISSUE THREAD

**Issue by eapache** [kakaroto/Beyond20#862] opened 2021-08-19 02:58 UTC
**Is your feature request related to a problem? Please describe.**
Some classes/features provide conditional advantage/disadvantage on certain skill checks. For example, with Blood Hunter's "Hunter's Bane" feature, D&D Beyond gives you the following to indicate advantage on certain Arcana checks:

![advantage1](https://user-images.githubusercontent.com/1706826/129999827-3f114c36-fb25-4a1f-a2a4-333cc82111d0.png)

And

![advantage2](https://user-images.githubusercontent.com/1706826/129999828-5b2bb82c-40af-4dda-b31e-baa09dd754db.png)

Beyond20 detects this flag and automatically rolls _all_ my Arcana checks with advantage, even when I have the "Type of Roll" setting to "Normal Roll". I don't expect the extension to know when advantage is applicable or not, but since it is only conditional advantage (and a rare condition, at that), it would be nice if it didn't do it by default.

**Describe the solution you'd like**
If the extension can detect when there is conditional flavour text, don't roll with advantage/disadvantage by default.

**Describe alternatives you've considered**
Alternatively, perhaps a setting to disable the auto-detection of advantage/disadvantage entirely? Or something else that makes more sense? This is a minor annoyance at best.

**Additional context**
This behaviour feels intentional to me, and I appreciate the likely intent to be helpful and detect advantage automatically. It may even be appropriate in a lot of cases? It's just gotten annoying for me that I keep rolling unrelated Arcana checks and have to remember to ignore the accidental advantage roll.

P.S. Thanks for the amazing extension!

**Comment by kakaroto** [comment] 2021-08-19 05:27
This is a known issue (for a long time now). See issue #408
Basically what I want is for those situational skill checks to query the user for whether or not to apply the advantage or not.
Closing as duplicate of #408.
Thanks!

**Closed by kakaroto** 2021-08-19 05:27 UTC
Labels: bug, duplicate
