### ISSUE TITLE
Allow Token Name override for VTT HP syncing

### ISSUE THREAD

**Issue by somanyrobots** [kakaroto/Beyond20#463] opened 2020-07-19 17:57 UTC
I usually have my character sheets named as firstname + lastname, but very often VTT tokens are only labeled with first names. It'd be nice if there were a per-character setting to override token names, so HP syncing can still work if the token name isn't identical to the character sheet name. This'd also be useful for any other situation where the token gets modified to a different name, which feels like a reasonably common circumstance.

Happy to try PRing this if you're amenable.

**Comment by Aeristoka** [comment] 2020-07-19 18:03
HP Syncing has nothing to do with the Token name, it has to do with the name on the Character Sheet, in example:
![image](https://user-images.githubusercontent.com/7988297/87881611-ab65e000-c9b7-11ea-8e70-62003887c70c.png)

Character name on DnDBeyond & FoundryVTT "Terry Tortoise", HP Sync will work just fine. Token name: "Terry", HP Sync doesn't care (exactly the same on Roll20)

So the only real issue is if the Character name on the DnDBeyond Character sheet changes, or the Character name on the Roll20/FoundryVTT character sheet (not the token) changes.

**Comment by somanyrobots** [comment] 2020-07-19 19:13
Ah, ok! Then the issue is that my DM's being lazy about character sheets. Thanks for the quick info!

**Comment by Aeristoka** [comment] 2020-07-19 22:34
No worries! If the issue is resolved, please close it.

**Comment by Aeristoka** [comment] 2020-07-19 23:24
@kakaroto please close.

**Closed** 2020-07-20 02:55 UTC
