### ISSUE TITLE
Does not support the new Encounter Builder/Combat tracker in DND Beyond

### ISSUE THREAD

**Issue by etriebe** [kakaroto/Beyond20#124] opened 2020-03-12 22:51 UTC
The new encounter builder and combat tracker is not supported yet. For example, this is the new combat tracker, which would be nice to be able to click on the actions on the right side and roll in Roll20. 

![image](https://user-images.githubusercontent.com/7503160/76574327-33236700-6479-11ea-962a-8cd010058879.png)

And here is what it looks like when running the encounter. 

![image](https://user-images.githubusercontent.com/7503160/76574575-e7bd8880-6479-11ea-8e33-52183e6eb6bb.png)

**Comment by kakaroto** [comment] 2020-03-12 22:56
Thanks for reporting. It's already been fixed in the dev version, so you can expect it fixed in this week's release.
Closing as duplicate of #104

**Comment by etriebe** [comment] 2020-03-12 22:57
Fantastic! Looking forward to it!

**Closed by kakaroto** 2020-03-12 22:56 UTC
Labels: duplicate
