### ISSUE TITLE
Radiance of the Dawn Parsing Issue

### ISSUE THREAD

**Issue by authyrtyr** [kakaroto/Beyond20#583] opened 2020-11-13 19:47 UTC
The Light Domain Cleric's Channel Divinity "Radiance of the Dawn" is not parsing correctly. It's splitting the roll in two. You can roll either half as 2d10 or d20+{Cleric Level} but there should be one roll for 2d10+{Cleric Level} instead.
![Capture](https://user-images.githubusercontent.com/8037494/99114644-1ec2db80-25bf-11eb-896e-37728c3725c7.PNG)

I'm using Chrome and connecting it with Roll20

**Comment by heizusan** [comment] 2020-12-04 03:17
This looks very similar to my just reported issue [#598](https://github.com/kakaroto/Beyond20/issues/598).

**Comment by Aeristoka** [comment] 2020-12-04 03:23
Your issue is a duplicate of this @heizusan

**Comment by kakaroto** [comment] 2020-12-08 02:38
And both are duplicates of #531
The problem is in how the data is presented on the page by D&D Beyond and fixing it is going to be a nightmare.

**Closed by kakaroto** 2020-12-08 02:38 UTC
