### ISSUE TITLE
Skyblinder Staff does not roll as Quarterstaff for attacks

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#511] opened 2020-09-12 21:49 UTC
When you click on the crossed swords in DNDBeyond, it displays the description but does not roll the attack.

![image](https://user-images.githubusercontent.com/29684482/93005558-b18bbf00-f517-11ea-9d2b-da03d45a27d6.png)

On Roll20

![image](https://user-images.githubusercontent.com/29684482/93005564-ca947000-f517-11ea-92ba-9d45a6ad298a.png)

Link to the magic item
https://www.dndbeyond.com/magic-items/skyblinder-staff

**Comment by DarrynGlass** [comment] 2020-09-12 21:53
A note on the forum indicates this may be because the staff is not setup correctly....
https://www.dndbeyond.com/magic-items/skyblinder-staff

"One of the players in the game I'm running was trying to make melee attacks with this using the digital dice and it wasn't correctly rolling or coming across using VTT. We figured out it seems to be because its base item type is set to "item" rather than "weapon"."

**Comment by kakaroto** [comment] 2020-09-12 21:58
FAQ entry about this : https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs
Duplicate of #99, #111 and #240

**Closed by kakaroto** 2020-09-12 21:58 UTC
