### ISSUE TITLE
Chaos Bolt does not roll properly when d8's match

### ISSUE THREAD

**Issue by j-schoch** [kakaroto/Beyond20#701] opened 2021-02-27 02:30 UTC
**Describe the bug**
When casting Chaos Bolt (available via my Izzet Engineer background), there are two behaviors expected:

1. The initial 2d8 **do not** match, and the numbers rolled represent the caster's options of damage type based on the damage type table in the spell description.
2. The initial 2d8 **do** match, and the number rolled forces the damage type based on the damage type table in the spell description.

When I cast this spell on D&D Beyond while linked to Foundry VTT and option 1 occurs, I get a popup giving me a choice of damage type.  

When option 2 occurs, nothing happens in Foundry.

**To Reproduce**
1. (if possible) Go to my character sheet and attempt to cast a Chaos Bolt using Beyond 20 to a Foundry VTT tab. 'https://ddb.ac/characters/26018438/unG2c0'
2. (if not possible to use my sheet) -- replicate my character as a level 13 artillerist artificer, with the Izzet Engineer background.  Select Chaos Bolt as a prepared spell, and attempt to cast it using Beyond 20 to a Foundry VTT tab.
3. Continue to cast it until you observe both options listed above occur (or rather, observe if option 2 does not occur properly)

**Expected behavior**

Option 1 is supported well, with a popup dialog to select damage type prior to the spell attack.

I expect with option 2, that the spell attack should occur in chat, along with all related damage dice with the appropriate damage type selected based on the damage type table in the Chaos Bolt spell description.

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

![Screenshot 2021-02-26 212510](https://user-images.githubusercontent.com/5287619/109372740-2c078b80-7879-11eb-8751-82e7ce3a38ec.png)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 88.0.4324.190 (Official Build) (64-bit)
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT
 - Error (not certain if this occurs in relation to the bug or as a coincidence) 

```
fvtt_script.js:2996 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at fvtt_script.js:2996
    at Array.map (<anonymous>)
    at FVTTDisplayer._postChatMessage (fvtt_script.js:2991)
    at FVTTDisplayer.postHTML (fvtt_script.js:2965)
    at Beyond20RollRenderer.postDescription (fvtt_script.js:2439)
```

**Additional context**
 'https://ddb.ac/characters/26018438/unG2c0'

**Comment by Aeristoka** [comment] 2021-02-27 04:10
Duplicate of #655 , this is already fixed in the Dev Version (slated for 2.3.1 release): https://github.com/kakaroto/Beyond20#developer-mode-installation

**Closed by Aeristoka** 2021-02-27 04:10 UTC
Labels: bug
