### ISSUE TITLE
Higher Level Casting results in multiple rolls in Roll20.

### ISSUE THREAD

**Issue by MicahZoltu** [kakaroto/Beyond20#465] opened 2020-07-19 23:23 UTC
![image](https://user-images.githubusercontent.com/886059/87887634-7c07af80-ca59-11ea-8987-42508f8defd5.png)

If I level up the spell and click the Spell Slot button in dndbeyond, the spell will show up 1 time in Roll20 for each level of the spell.  This means if I upcast a level 1 spell to level 3, I'll see 3 separate rolls in Roll20.  Each individual cast is correctly higher-level casted (rolls correct number of dice, indicates higher level cast, etc.), it is just rolled multiple times:
![image](https://user-images.githubusercontent.com/886059/87887679-bc672d80-ca59-11ea-9372-1c447f8f7536.png)

If I instead click the Cast on VTT button at the top, it correctly rolls once at higher level.

**Comment by Aeristoka** [comment] 2020-07-19 23:24
Duplicate of #459

**Closed** 2020-07-19 23:32 UTC
