### ISSUE TITLE
Rolling an attack just prints the item description

### ISSUE THREAD

**Issue by wilrodriguez** [kakaroto/Beyond20#1110] opened 2024-04-26 02:21 UTC
**Describe the bug**
Out of nowhere, everyone in my group is suddenly not getting their attacks rolled when you click on the roll button from the actions on your dndbeyond page, it just prints the item text.

**To Reproduce**
1. Go to your attacks and click one of them, any one of them and click the attack button
2. Look at roll20
4. See item text instead of your roll

**Expected behavior**
You should be rolling your attack damage when you click the attack button

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

https://github.com/kakaroto/Beyond20/assets/5179601/4e41a580-7686-4322-b01e-bf2ef7187d31

![Screenshot 2024-04-25 211418](https://github.com/kakaroto/Beyond20/assets/5179601/89331236-cceb-405f-a31d-99e717817d26)

**Browser Info (please complete the following information):**
 - Browser Firefox
 - Version 125.0.1 
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT:
 ```
 Error: Syntax error, unrecognized expression: . jquery-3.4.1.min.js:2:13061
    jQuery 7
        error
        tokenize
        select
        se
        find
        init
        k
    injectRollButton moz-extension://394a2ebf-4980-4c17-9518-ecdbc0d0c82e/dist/dndbeyond_character.js:8346
    documentModified moz-extension://394a2ebf-4980-4c17-9518-ecdbc0d0c82e/dist/dndbeyond_character.js:8997
Sending message:  
Object { action: "roll", character: {…}, type: "trait", roll: "", advantage: 0, whisper: 0, name: "Guardian Armor: Thunder Gauntlets", description: "Each of the armor’s gauntlets counts as a simple melee weapon while you aren’t holding anything in it, and it deals 1d8 thunder damage on a hit. A creature hit by the gauntlet has disadvantage on attack rolls against targets other than you until the start of your next turn, as the armor magically emits a distracting pulse when the creature attacks someone else.", "source-type": "action" }
dndbeyond_character.js:4677:17
Received response :  
Object { success: true, vtt: (1) […], error: null, request: {…} }
dndbeyond_character.js:4971:13
Beyond20: New side panel is : dndbeyond_character.js:8996:21
Error: Syntax error, unrecognized expression: . jquery-3.4.1.min.js:2:13061
    jQuery 7
    injectRollButton moz-extension://394a2ebf-4980-4c17-9518-ecdbc0d0c82e/dist/dndbeyond_character.js:8346
    documentModified moz-extension://394a2ebf-4980-4c17-9518-ecdbc0d0c82e/dist/dndbeyond_character.js:8997
```

**Comment by kakaroto** [comment] 2024-04-26 02:24
Hi,
See the release notes for the update from yesterday: https://www.patreon.com/posts/beyond20-v2-9-2-103008407
The 2.9.2 update has been posted to the mozilla addons, but it's pending review from the firefox team. Either install it from source, or switch to chrome in the meantime.
Closing as duplicate of #1107

**Comment by wilrodriguez** [comment] 2024-04-26 02:32
> Hi, See the release notes for the update from yesterday: https://www.patreon.com/posts/beyond20-v2-9-2-103008407 The 2.9.2 update has been posted to the mozilla addons, but it's pending review from the firefox team. Either install it from source, or switch to chrome in the meantime. Closing as duplicate of #1107

Thanks for the super quick reply! I should have looked at the closed issues.

**Comment by kakaroto** [comment] 2024-04-26 02:37
> Thanks for the super quick reply! I should have looked at the closed issues.

No worries. I actually kept it open so people can see it, but then I closed it after the chrome store published the update, and I thought FF was going to be close behind (this seems like the longest time it's taken FF to review/publish an update).
Enjoy!

**Comment by kakaroto** [comment] 2024-04-30 19:43
Firefox has made public the 2.9.2 release on their store! You can now update.
Thanks for your patience.

**Closed by kakaroto** 2024-04-30 19:43 UTC
Labels: bug, duplicate
