### ISSUE TITLE
Attacks and Damage will not roll with Digital Dice

### ISSUE THREAD

**Issue by Jacoloped** [kakaroto/Beyond20#347] opened 2020-06-03 13:25 UTC
I can send skill rolls, ability checks, and saving throws with the digital dice to Roll20, but attacks and damage rolls do now send.

**Comment by Aeristoka** [comment] 2020-06-03 13:28
Duplicate of #343 

DO NOT click on the Digital Dice areas, click on the Quick Roll button, or click on the weapon to pop out the sidebar and click the Beyond20 roll button
![image](https://user-images.githubusercontent.com/7988297/83642195-c09fc000-a56b-11ea-966f-5754b5000984.png)

**Comment by thelontx** [comment] 2020-06-03 16:55
Hello...  When I first tried the new release this morning, it appears that To Hit and Damage rolls were working successfully with Roll20.   i.e. result showed up inside Roll20 chat.

I now seem to see a reverted behavior, where stat/skill/save rolls in DnDBeyond go to R20 except Attack/Damage.   This appears to be the original issue raised here.  Between the original working condition and the subsequent not working condition, I was playing with the Digital Dice custom roll icon.  I do not know if that is related or not.  NOTE:  The rolls from the Digital Dice custom roll icon do not go to R20 either.

Related note:  When I click on the B20 quick roll icon indicated in the image, nothing happens. (saves, stats, skills, etc.)  If I click on the Digital Dice area, I get a successful roll in DnDBeyond with the results in R20 chat.

**Comment by thelontx** [comment] 2020-06-03 17:02
One possible additional clue... I don't know if this is related or not.  Attaching image from my R20 chat.  After a successful result for Attach/Damage, there was a skill roll that seemed to revert to the old graphics in R20 chat.  Then, there was another skill roll with the new graphics in R20 chat.
![Screen Shot 2020-06-03 at 11 59 02 AM](https://user-images.githubusercontent.com/5131752/83666083-fe174400-a591-11ea-9214-0a70958d8339.png)

**Comment by thelontx** [comment] 2020-06-03 17:06
Ah... I see.  The quick roll is on the icon to the left of the attack.   Works successfully with R20.

**Closed** 2020-07-08 04:42 UTC
Labels: D&D Beyond, enhancement
