### ISSUE TITLE
Beyond20 Crashing DnDBeyond Encounter Pages

### ISSUE THREAD

**Issue by Sammyj090** [kakaroto/Beyond20#791] opened 2021-05-06 15:00 UTC
**Describe the bug**
When Beyond20 extension is running in Chrome (Latest Version), and you are using the DnDBeyond.com Encounter Builder at the same time, the DnDBeyond Encounter Builder will crash.

**To Reproduce**
1. Go to '[DnDBeyond.com Encounter Builder](https://www.dndbeyond.com/my-encounters)'
2. Click on 'A Previously Created Encounter'
3. Run Encounter
4. Click between Monsters while you have a VTT (Roll20.com) open.

**Expected behavior**
The Encounter Builder Page on DnDBeyond.com will crash and only leave a button reading "Report Feedback"

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Comment by Aeristoka** [comment] 2021-05-06 15:03
Closing as duplicate of #775
note a workaround I posted about to prevent the encounters from crashing : #775 (comment)

**Closed by Aeristoka** 2021-05-06 15:03 UTC
Labels: bug
