### ISSUE TITLE
Totals bar sums both single and double handed damage when rolling with a versatile weapon while raging with DnD Beyond's Virtual Dice Enabled.

### ISSUE THREAD

**Issue by Carlingr** [kakaroto/Beyond20#911] opened 2022-01-10 00:55 UTC
**Describe the bug**
The totals bar shown in the Roll-20 chat sums both the single and double handed damage when rolling with a versatile weapon while raging with DnD Beyond's Virtual Dice Enabled.

**To Reproduce**
1. Open or create a babarian charecter in D&D Beyond.
2. In Beyond 20's settings, toggle both "Use D&D Beyond's Digital Dice" and "Barbarian: Rage! You are raging, ARRGGHHHHHH" on.
3. Initiate a damage roll for a versatile weapon.
4. In Roll20, see that an attack roll is displayed with both one-handed and two-handed damage, followed by a box with 2 rage damage. But then a blank Totals bar is displayed, followed by a second box with a total of both the single and double handed damage plus the two rage damage.

**Expected behavior**
The totals bar should display the total damage for one and two handed attacks separately, 

**Screenshots**
Output as it exists: 
![image](https://user-images.githubusercontent.com/24228206/148697467-35b7ba83-3981-4cc2-ac43-f70c52d50b30.png)

Rendering of possible look for expected behavior: 
![image](https://user-images.githubusercontent.com/24228206/148707983-3752730c-1f62-43d6-b2b4-5bec7be03165.png)

**Browser Info (please complete the following information):**
Firefox 95.0.1 (64-bit) for Ubuntu with Beyond 20 Version 2.6.0

**Comment by Aeristoka** [comment] 2022-01-10 00:59
Duplicate of #814 

Same suggestion, set your Versatile preference to One or Two handed

**Comment by kakaroto** [comment] 2022-01-10 01:01
This is a regression. It used to output separate totals for 1 handed and 2 handed totals.

**Comment by Aeristoka** [comment] 2022-01-10 01:02
Wait, you're breaking crap now @kakaroto ?

**Comment by Aeristoka** [comment] 2022-01-10 01:03
(Still better to set your Versatile preference regardless)

**Comment by kakaroto** [comment] 2022-01-10 01:04
> Wait, you're breaking crap now @kakaroto ?

No, you did! 
The `has_versatile` is always false here : 
https://github.com/kakaroto/Beyond20/blob/master/src/common/roll_renderer.js#L525

And that's likely caused by #906 😝

**Comment by Aeristoka** [comment] 2022-01-10 01:05
Well...

**Comment by Carlingr** [comment] 2022-01-10 01:16
I don't think this necessarily merits it's own bug report since it seems to be part of this broader issue (though I can certianly file it seperately if that's helpful) but without virtual dice on dnd beyond doesn't show any total, and only shows the rage damage on the 2 hand weapon: 
![image](https://user-images.githubusercontent.com/24228206/148708639-ffcd084a-9408-4f27-8bbc-3067842f69eb.png)

I turned on the virtual dice in the first place because it was the only way I could get Beyond 20 to pipe my roll to roll 20 when I clicked on the two handed damage on my dnd beyond charecter sheet:
![image](https://user-images.githubusercontent.com/24228206/148708839-9c17c9f8-9829-477f-b7d3-36ec8a7c65e6.png) though it occurs to me now that clicking the one handed damage also rolls two handed damage. I wonder if it would be phesable to implement a set of keys to switch between 1/2 handed damage, similar to how Advantage/Disadvantage is handled?

**Comment by Aeristoka** [comment] 2022-01-10 03:38
> I don't think this necessarily merits it's own bug report since it seems to be part of this broader issue (though I can certianly file it seperately if that's helpful) but without virtual dice on dnd beyond doesn't show any total, and only shows the rage damage on the 2 hand weapon: ![image](https://user-images.githubusercontent.com/24228206/148708639-ffcd084a-9408-4f27-8bbc-3067842f69eb.png)
> 
> I turned on the virtual dice in the first place because it was the only way I could get Beyond 20 to pipe my roll to roll 20 when I clicked on the two handed damage on my dnd beyond charecter sheet: ![image](https://user-images.githubusercontent.com/24228206/148708839-9c17c9f8-9829-477f-b7d3-36ec8a7c65e6.png) though it occurs to me now that clicking the one handed damage also rolls two handed damage. I wonder if it would be phesable to implement a set of keys to switch between 1/2 handed damage, similar to how Advantage/Disadvantage is handled?

Precisely what this setting is for: 
![image](https://user-images.githubusercontent.com/7988297/148715795-a3360c0e-d9fb-4f8d-a1a5-cf6a37e9a8bf.png)

**Comment by Aeristoka** [comment] 2022-01-10 03:40
> I don't think this necessarily merits it's own bug report since it seems to be part of this broader issue (though I can certianly file it seperately if that's helpful) but without virtual dice on dnd beyond doesn't show any total, and only shows the rage damage on the 2 hand weapon: ![image](https://user-images.githubusercontent.com/24228206/148708639-ffcd084a-9408-4f27-8bbc-3067842f69eb.png)
> 
> I turned on the virtual dice in the first place because it was the only way I could get Beyond 20 to pipe my roll to roll 20 when I clicked on the two handed damage on my dnd beyond charecter sheet: ![image](https://user-images.githubusercontent.com/24228206/148708839-9c17c9f8-9829-477f-b7d3-36ec8a7c65e6.png) though it occurs to me now that clicking the one handed damage also rolls two handed damage. I wonder if it would be phesable to implement a set of keys to switch between 1/2 handed damage, similar to how Advantage/Disadvantage is handled?

Beyond20 does not need Digital Dice to roll damage, you can click on the Crossed Swords icon to have it roll Attack and Damage both. Beyond20 existed far before DnDBeyond Digital Dice did, and worked wonderfully then. The only benefit to clicking the dice count with Digital Dice on is that you roll the damage only, but you can also click the Crossed Swords while having "Auto Roll Damages and Crits" off, and it will roll your to-hit only.

**Closed** 2022-01-11 05:51 UTC
Labels: bug

**Comment by kakaroto** [comment] 2022-01-12 07:28
> I don't think this necessarily merits it's own bug report since it seems to be part of this broader issue (though I can certianly file it seperately if that's helpful) but without virtual dice on dnd beyond doesn't show any total, and only shows the rage damage on the 2 hand weapon: ![image](https://user-images.githubusercontent.com/24228206/148708639-ffcd084a-9408-4f27-8bbc-3067842f69eb.png)
> 

The reason there's no totals there (or separate boxes for each damage) is because without digital dice, the rolls are made by Roll20, and we have very little control over that. We can't get the roll results from it so we can't calculate the totals. If you hover on the numbers, you'll see the difference between "rolled by roll20" versus "this is the number to display".

> though it occurs to me now that clicking the one handed damage also rolls two handed damage. I wonder if it would be phesable to implement a set of keys to switch between 1/2 handed damage, similar to how Advantage/Disadvantage is handled?


You can already do that, click the 'more options' then set a custom hotkey : 
![image](https://user-images.githubusercontent.com/27990/149082723-ef592276-4065-4953-b160-5067606ebe65.png)

![image](https://user-images.githubusercontent.com/27990/149082802-ff4106dc-e519-488e-af30-f0a05f3ded7d.png)
