### ISSUE TITLE
Display on Roll20 Button for spells doesn't work

### ISSUE THREAD

**Issue by KMontag42** [kakaroto/Beyond20#29] opened 2019-08-03 18:20 UTC
https://www.dndbeyond.com/spells/enlarge-reduce#

https://gyazo.com/8de62605c9d351cdfedbc233dd2c1b52

This button doesn't work when trying to send the spell's info to Roll20.

Is there something I should update or do differently?

Thanks!

**Comment by kakaroto** [comment] 2019-08-04 02:41
Hi, thanks for reporting!
This is a duplicate of #22 which was already fixed. I'll be working on making a new release soon with this fix.
Since it's already been fixed, you can use the development version (see the README for how to do that) to get it fixed for you.
Thanks!

**Closed by kakaroto** 2019-08-04 02:41 UTC
