### ISSUE TITLE
Switching between monsters when using Beyond20 extension causes the DDB Combat tracker to crash

### ISSUE THREAD

**Issue by oldmangraye** [kakaroto/Beyond20#786] opened 2021-05-01 18:55 UTC
I've just noticed that when I use the DDB combat tracker and when Beyond20 is activated using either digital dice or Roll20 dice, switching between monsters in the encounter combat tracker crashes the DDB combat tracker. I've verified that the DDB combat tracker works fine if I disable the Beyond20 extension, so unsure what might be causing the crash. Seems to happen only when I switch between monsters. 

Note: in the screenshots the Beyond20 dice roller embeds are showing as with advantage because of the Mac keypresses for taking a screenshot.

Using chrome Version 90.0.4430.93 (Official Build) (x86_64), Beyond 20 chrome extension 2.4.1, and MacOS 11.3 (20E232)

![Screen Shot 2021-05-01 at 11 50 15 AM](https://user-images.githubusercontent.com/83511032/116792180-ec753f80-aa73-11eb-8cb4-a14c52468ec8.png)
![Screen Shot 2021-05-01 at 11 50 26 AM](https://user-images.githubusercontent.com/83511032/116792182-eda66c80-aa73-11eb-8ce8-b6b85f4364b2.png)
![Screen Shot 2021-05-01 at 11 50 34 AM](https://user-images.githubusercontent.com/83511032/116792184-eed79980-aa73-11eb-8960-942632ab0f67.png)
![Screen Shot 2021-05-01 at 11 50 42 AM](https://user-images.githubusercontent.com/83511032/116792186-f008c680-aa73-11eb-9f0d-e3f96ce3f862.png)

**Comment by Aeristoka** [comment] 2021-05-01 18:59
This is an issue on the DnDBeyond side, @kakaroto has reported it to DnDBeyond. It has to do with them adding the Digital Dice to Monsters (still wildly Alpha), and they need to fix things from their side so far as I understand it.

**Comment by oldmangraye** [comment] 2021-05-01 19:10
Thanks for the update on this. I guess I'll track encounters the old fashioned way!

**Comment by Aeristoka** [comment] 2021-05-01 19:43
> Thanks for the update on this. I guess I'll track encounters the old fashioned way!

Ideally (and I don't know why they DON'T have this already), DnDBeyond should have a Toggle to Disable Digital Dice.

Or rather, they should have 3 of those toggles by now:

1. Global (no Digital Dice anywhere)
2. Character sheet (exists)
3. Monsters

**Comment by kakaroto** [comment] 2021-05-02 11:48
Closing as duplicate of #775 
note a workaround I posted about to prevent the encounters from crashing : https://github.com/kakaroto/Beyond20/issues/775#issuecomment-826119391

**Closed by kakaroto** 2021-05-02 11:48 UTC
