### ISSUE TITLE
Foundry VTT Integrate with targeting system, native attack rolls

### ISSUE THREAD

**Issue by akrigline** [kakaroto/Beyond20#420] opened 2020-06-24 12:09 UTC
Foundry VTT has a robust automation module [minor-qol](https://gitlab.com/tposney/minor-qol) which cuts a lot of busywork out from a DM's plate while running combat.

It would be excellent if Beyond20's rolls could be wired up to the foundry systems in such a way that would trigger minor-qol's events.

This could require a much more significant setup process on the FoundryVTT host side, particularly for spells. I am still a novice with understanding FoundryVTT's 5e flows but here's my observations:

It seems that the 5e system module uses 'item' entities for both Spells and Weapon attacks, and Beyond20 would have to try title-matching spells/attacks from D&D Beyond with existing items in order to properly hook into the flow.

Goals:
- Allow 5e system's "Draw template when casting spell" to happen.
- Pretend to be foundry-based rolls enough for other Foundry combat modules to operate on beyond20 initiated rolls.

**Comment by Aeristoka** [comment] 2020-06-28 06:17
I believe related to #218 (at least in part)

**Comment by kakaroto** [comment] 2020-06-28 19:37
Yep, that's what #218 is for. I thought of doing the template thing myself but figured it might just be better to create an item and let it roll natively, as that would take care of the template, minor-qol and many other possible module enhancements to rolls.
Will probably add a 'template to use' kind of setting like the one for roll20, so you can decide to do that or use the Beyond20 renderer.
Closing this as it's a duplicate of #218, though it has more details, it's now referenced from the other issue.

**Closed by kakaroto** 2020-06-28 19:37 UTC
Labels: duplicate
