### ISSUE TITLE
Avatar image squished on description open

### ISSUE THREAD

**Issue by LorduFreeman** [kakaroto/Beyond20#869] opened 2021-09-23 12:48 UTC
Heya. First of all: Nice to see there's an update and my new CSS made it in. It seems not the most recent addition was merged or integrated somehow, because the `last-child` css formatting is still in it, causing inconsistent formatting on crits with only a single line of damage, with the Crit line being bigger than regular damage:
![image](https://user-images.githubusercontent.com/72170114/134508012-2278b438-02a1-42b2-8957-cd0c9ba44c66.png)

This css rule is not existing in the pull request files anymore because I removed it at some point.

**Comment by LorduFreeman** [comment] 2021-09-23 13:05
Another thing I noticed: Expanding the description seems to slightly shift the positions/size of the Chat Card title and the character image.

**Comment by kakaroto** [comment] 2021-09-25 02:53
Humm... 
This is the last PR from you that I merged : https://github.com/kakaroto/Beyond20/pull/846
I also think you fixed the `last-child` stuff in it (I don't see it in https://github.com/kakaroto/Beyond20/blob/master/src/extension/beyond20.css), so I'm not sure.... 
Humm... I think the issue is probably that there hasn't been a new release of the FVTT module so you might have two conflicting css being injected into your Foundry instance? 
The only thing I added recently was the support for showing the avatar image next to the attack name (and I hope I did it correctly!).

**Comment by LorduFreeman** [comment] 2021-09-25 20:11
I derped, that was indeed it. Should I open another issue for the avatar image squishing on description open?

**Comment by kakaroto** [comment] 2021-12-27 21:42
Humm... I'm not actually seeing the avatar getting squished on description open.
Closed :
![image](https://user-images.githubusercontent.com/27990/147509023-7797a6ec-4e64-4e95-abbb-66397d71a5ac.png)
Open : 
![image](https://user-images.githubusercontent.com/27990/147509044-8fdaf4c0-42a3-4a6d-9d10-f6b2fbc9aa64.png)

**Comment by kakaroto** [comment] 2021-12-27 21:43
Closing this issue as it's not reproducible and I'm not sure what needs to be done here. If you can provide more information (or even a CSS fix!) then feel free to re-open the issue, thanks!

**Closed by kakaroto** 2021-12-27 21:43 UTC
Labels: bug

**Comment by kakaroto** [comment] 2021-12-31 21:23
Ha! I was able to reproduce it with a different character, I didn't get it on the first one because they had a square avatar, but the issue happens when the avatar as a non 1:1 aspect ratio.
I fixed it by doing : 
```css
aspect_ratio: 1;
object-fit: contain;
```
so it looks the same as on DDB... Though `aspect-ratio` is technically 'experimental', it should be supported by any browser that can run Foundry.
