### ISSUE TITLE
Custom modifier applied twice when applied to Druid Wildshape dice rolls

### ISSUE THREAD

**Issue by ArsonKoala** [kakaroto/Beyond20#1074] opened 2023-07-23 20:44 UTC
When using custom modifiers (i.e. +1 magic bonus, +1d4 from bless) on dice rolls in Wildshape stat block, modifier being applied twice (+1+1 instead of +1, +1d4+1d4 instead of +1d4)

**To Reproduce**
Go to character sheet, open extras, click desired wildshape to open statblock on right display, apply custom modifier either through beyond20 dropdown or custom hotkey, click dice roll button.

**Expected behavior**
If custom modifier is +1 to roll or +1 to damage, should be applying +1 not +1+1.

**Browser Info (please complete the following information):**
 - Firefox
 - 115.0.2 

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by kakaroto** [comment] 2023-07-23 21:22
I'm not seeing that behavior when using custom modifiers configured on the character sheet
![image](https://github.com/kakaroto/Beyond20/assets/27990/30f1b7c0-944c-4274-8d9f-39926a9f2443)
But if I use a hotkey, I do see it:
![image](https://github.com/kakaroto/Beyond20/assets/27990/ae20b1d5-b243-4920-98c0-2afa59beda84)

**Comment by kakaroto** [comment] 2024-11-17 00:04
I am unable to reproduce this issue anymore, I don't remember it getting explicitely fixed at any time recently, but it might have been fixed as a side effect of some other changes.
I'm closing this issue now since it looks like it works. If you do still encounter it please reopen the issue with step by step instructions on how to get it to occur again.
Thank you.

**Closed by kakaroto** 2024-11-17 00:04 UTC
Labels: bug
