### ISSUE TITLE
Integration of DnDBeyond's Dice Roller

### ISSUE THREAD

**Issue by Inshal240** [kakaroto/Beyond20#237] opened 2020-05-05 18:36 UTC
DnDBeyond released its dice rollers today which rolls within the DnDBeyond website and displays the result along with appropriate modifiers. Is there any chance this result could be carried over to Roll20? That is, rather than roll twice, the result of the roll in DnDBeyond is simply displayed within Roll20. 

Roll20 lacks dice animations so this could be a really neat feature to have!

**Comment by Aeristoka** [comment] 2020-05-05 18:37
Duplicate of #220 , please close.

**Closed** 2020-05-05 20:33 UTC
