### ISSUE TITLE
Feature Request - Setting to Add Custom Domains to Activate Beyond20 On (Automate Foundry Activation)

### ISSUE THREAD

**Issue by FroggMaster** [kakaroto/Beyond20#897] opened 2021-12-08 08:27 UTC
**Is your feature request related to a problem? Please describe.**
Having to click the Beyond20 Extension to activate it within a Foundry Install. This is due to the extension not automatically having permission to modify the website. 

**Describe the solution you'd like**
An option in the settings for Custom Domains. 
You would be able to provide multiple custom domains, that would enable Beyond20 automatically on them. 

**Describe alternatives you've considered**
Modifying the chrome extensions manifest file myself.

**Comment by kakaroto** [comment] 2021-12-08 21:26
That's not actually possible to do that way because of permission restrictions. We can already detect if Foundry is running, but when you click the extension icon, you're actually telling Chrome to authorize the extension to run its code on that page. It's not a restriction we have on Firefox however.
That being said, this is basically a duplicate of this issue : https://github.com/kakaroto/Beyond20/issues/179
Once I figure out how to make that work, it would basically allow you to click on the icon once, and it would then prompt you to permanently allow the extension to run on that domain and you wouldn't need to click it again in the future.
I've tried to do it once but it wasn't working the way it needed to, so it's been shelved until I revisit it.

**Closed by kakaroto** 2021-12-08 21:26 UTC
Labels: duplicate

**Comment by FroggMaster** [comment] 2021-12-13 07:36
There is a way to read variables / arrays from JS scripts within the manifest to apply dynamic permissions. 

My Thoughts:
A section within the extensions popup/settings where a URL can be included. This would be tied to a JS Variable or array for each value. (Ex. CustomURL1, CustomURL2)

In addition to the user supplying the VTT URL they would need to define what VTT they're using from a list of pre-defined options. Foundry, OtherVTTs. (My primary concern here really is foundry, but I'm sure other VTT's may benefit too.)

Example Image:
[Example Image](https://i.imgur.com/P6aZr4W.png)

Alternatively as mentioned in #179 you can perform chrome.permissions request 
There's more information defined in the developer documentation: [Chrome Dev Documentation](https://developer.chrome.com/docs/extensions/reference/permissions/)

Which would require the addition of the following in the manifest.json
`"optional_permissions": [ "webNavigation", "http://*/*", "https://*/*" ],` 

In addition to request these permissions, as you mentioned at least one time.
