### ISSUE TITLE
Attack Rolls, Check and Saving throws don't get displayed in FoundryVTT

### ISSUE THREAD

**Issue by Janders797** [kakaroto/Beyond20#1143] opened 2024-07-07 05:38 UTC
Neither of these 3 show up in chat when using a DNDBeyond character or NPC. Damage rolls and custom rolls still show up. Even when using a newly created world.

Interestingly, when using DiceSoNice, it does display the D20 on Foundry. It just doesn't show the result in chat.

I don't run into this problem when running a game on Roll20, only Foundry.

**Comment by Janders797** [comment] 2024-07-07 05:56
We're using the newest version of Foundry, I use Chrome and at least 1 player uses Firefox.

**Comment by kakaroto** [comment] 2024-07-07 07:08
The issue is the dnd5e system.older versions of the system don't have the issue. See https://github.com/kakaroto/Beyond20/issues/1127
Closing as duplicate.

**Closed by kakaroto** 2024-07-07 07:08 UTC
Labels: bug, duplicate
