### ISSUE TITLE
Not recognizing the currently open sidebar

### ISSUE THREAD

**Issue by fishdude100** [kakaroto/Beyond20#1119] opened 2024-05-07 18:26 UTC
I was in the middle of a game and the extension was working (1:23pm CDT).  Our party leveled up and now I'm unable to cast spells or saving throws to Roll20.  Attack rolls with weapons still work.  

Also, two other players experienced the same issue as me.  We received the following error message when trying to cast a spell:

_Not recognizing the currently open sidebar_

I attempted the following:
1) cleared Chrome Browser
2) tried using in Brave & Edge
3) reinstalled Beyond 20 on each

None of these worked.

**Comment by kakaroto** [comment] 2024-05-07 18:57
Looks like DDB made yet another change to their character sheet today :(
I can confirm it broke the extension, thanks for reporting it.

**Comment by Rupert-117** [comment] 2024-05-07 19:31
There may also be an issue, unsure if its a problem with Beyond or Beyond20, where saving throws aren't rolled with the bonuses. Probably related to the changes to char sheets if so.

**Comment by dmportella** [comment] 2024-05-08 08:43
can confirm there were style changes in a number of places

**Comment by GaiusNale** [comment] 2024-05-08 15:35
Presently it's not letting me cast spells either

**Comment by kakaroto** [comment] 2024-05-11 02:23
Fixed in https://github.com/kakaroto/Beyond20/commit/b3983f990835abde01f174ae87feacffadcf97c6

Version 2.9.3 was just released (pending approval on browser stores) with the fix. See: https://www.patreon.com/posts/beyond20-v2-9-3-104033738

**Closed by kakaroto** 2024-05-11 02:23 UTC
Labels: bug
