### ISSUE TITLE
Beyond20 rolls not activating Better Rolls module

### ISSUE THREAD

**Issue by Wokeye27** [kakaroto/Beyond20#661] opened 2021-01-19 09:21 UTC
Hi, 
I cannot get the rolls from DDB to activate the Better Rolls module. Same effect on local server and the Forge. I've got this module running on both DDB and chrome browser foundry, so the rolls are showing up but are default foundry. 

![image](https://user-images.githubusercontent.com/77101610/105013773-b3e8c180-5a93-11eb-905f-360361d4051b.png)

**Comment by Aeristoka** [comment] 2021-01-19 14:50
Right, this is exactly how it works right now. @kakaroto is in the middle of implementing an option to have them be native rolls as noted in #218 , but it isn't there yet.

**Comment by kakaroto** [comment] 2021-09-10 00:21
Closing as it's a duplicate of #218

**Closed by kakaroto** 2021-09-10 00:21 UTC
