### ISSUE TITLE
Unable to roll from DNDBeyond to Roll20

### ISSUE THREAD

**Issue by jeffgillispie114** [kakaroto/Beyond20#1071] opened 2023-07-05 23:22 UTC
**Describe the bug**
Before the update, I was able to roll from DNDBeyond to Roll20, but now I am not able to. Beyond20 is stating that there is not a VTT available.

**To Reproduce**
1. Open a Roll 20 game
2. Open a DND Character
3. Attempt to roll an attack or any other dice from DNDBeyond
4. No dice are rolled to Roll20, but still roll in DNDBeyond.

**Expected behavior**
Attack Roll, Spell attack, or damage goes to Roll20.

**Screenshots**
![image](https://github.com/kakaroto/Beyond20/assets/53870118/2c64a764-c13e-45e5-9bc1-2c587959462d)
![image](https://github.com/kakaroto/Beyond20/assets/53870118/0b40fbd0-d0ac-46e1-b3d0-f3feb083ab68)
![image](https://github.com/kakaroto/Beyond20/assets/53870118/aebedb6a-76fb-4384-996e-0401dd9e68e5)
![image](https://github.com/kakaroto/Beyond20/assets/53870118/73f2fc9e-e88f-4c39-93f3-bf0e848e87db)
![image](https://github.com/kakaroto/Beyond20/assets/53870118/2cb89a83-6710-452d-a2cd-28f92bff2425)
![image](https://github.com/kakaroto/Beyond20/assets/53870118/e4a61a43-509b-4325-8c38-4e451c055783)
![image](https://github.com/kakaroto/Beyond20/assets/53870118/6b085b0c-97e4-4816-829c-f8d8ffeb0a12)

**Browser Info (please complete the following information):**
 - Chrome
 - 114.0.5735.199
 - Screenshots provided for the Console

**Additional context**
https://ddb.ac/characters/46281355/k2TS8c

**Comment by kakaroto** [comment] 2023-07-05 23:26
Hi,
This isn't related to the update, but rather something changed in Roll20 about 4 hours ago. I think it might be related to a DDoS protection they've just added, as people are seeing this prompt when they open Roll20:

![image](https://github.com/kakaroto/Beyond20/assets/27990/ede37fb8-d2af-412b-8a34-7a42b6e35df3)

After that, your campaign URL becomes like this: `https://app.roll20.net/editor/?oauth_check=1` which is new. If you remove the `?oauth_check=1` portion of the URL, then it should work again without issues.
We're hoping that this is a temporary issue while Roll20 deals with some sort of attack, but if not, we'll be releasing a minor update soon to take care of this issue.

Leaving this issue open in case someone else comes to report the problem.

**Comment by Alehound83** [comment] 2023-07-06 00:55
I ran into this same issue and removing the **?oauth_check=1** was the solve for me as well.

**Comment by Ragnarok2060** [comment] 2023-07-06 01:07
Same issue for myself and my group right now. Removing the ?oauth_check=1 didn't help though.

**Comment by jeffgillispie114** [comment] 2023-07-06 01:19
It did fix for me. I did refresh my DNDBeyond sheet after that. Also I have seen where DND will actually roll it and I am having to wait until it actually sends it to Roll20.

**Comment by ibaaske** [comment] 2023-07-06 04:26
Removing ?oauth_check=1 fixed it for me as well. I see you already have an updated version with a wildcard. Thank you!

**Comment by Snigy24** [comment] 2023-07-06 21:38
Hey, i remove the ?oauth_check=1, the error not appear anymore but still not appear in roll20

**Comment by Aeristoka** [comment] 2023-07-06 21:39
> Hey, i remove the ?oauth_check=1, the error not appear anymore but still not appear in roll20

If you're using Chrome, just pull the update to Beyond20 2.9.1.

If you use Firefox or otherwise, just use Chrome for now (until the extension is approved on those Extension Marketplaces).

**Comment by Snigy24** [comment] 2023-07-06 21:42
> > Hey, i remove the ?oauth_check=1, the error not appear anymore but still not appear in roll20
> 
> If you're using Chrome, just pull the update to Beyond20 2.9.1.
> 
> If you use Firefox or otherwise, just use Chrome for now (until the extension is approved on those Extension Marketplaces).

well that really helps, thanks mate

**Comment by CasCas96** [comment] 2023-07-08 18:37
Had the same problem today and another player also. we both erased the part of the URL and it started working again

**Comment by Slightlylyons** [comment] 2023-07-10 02:10
The Firefox store appears to have 2.9 as the current version, not 2.9.1

**Comment by Aeristoka** [comment] 2023-07-10 02:11
> The Firefox store appears to have 2.9 as the current version, not 2.9.1

The Firefox and Edge stores both have still not approved the 2.9.1 update.

**Comment by Yinepuhotep** [comment] 2023-11-28 05:01
Still having this problem on Roll20, with the 2.9.1 update. Even fixing the URL issue doesn't solve the problem. Beyond20 just can't seem to find the VTT at all.

**Comment by kakaroto** [comment] 2023-11-28 05:30
> Still having this problem on Roll20, with the 2.9.1 update. Even fixing the URL issue doesn't solve the problem. Beyond20 just can't seem to find the VTT at all.

The issue has been fixed with the 2.9.1 released back in july (I didn't realize we forgot to close this issue), and I just tested without problem.
It's more likely that the problem is from your side.

Can you click on the beyond20 icon on roll20's page and check if the "Send to" option has roll20 selected, or "all vtt" and not a specific campaign?

![image](https://github.com/kakaroto/Beyond20/assets/27990/458f73f7-639b-4603-9d31-a539fbcce8f3)

If that doesn't resolve it, please open a new issue with more details about your environment.
Thanks.

**Closed by kakaroto** 2023-11-28 05:30 UTC
Labels: bug
