### ISSUE TITLE
Monster descriptions are sometimes mixed when viewing them on Encounter Builder

### ISSUE THREAD

**Issue by GSBicalho** [kakaroto/Beyond20#1066] opened 2023-06-04 03:01 UTC
**Describe the bug**
In the encounter builder, when seeing an encounter, the extension can cause the text of one monster to weirdly mix with the other. For example, an encounter with Ogremoch and a few flail snails will initially show Ogremoch's Summon Elementals ability as

![image](https://github.com/kakaroto/Beyond20/assets/5908933/93fe7bbf-119e-40e9-af1d-acb80b265087)

If you visualize the Flail Snail, then look at Ogremoch again, you will see

![image](https://github.com/kakaroto/Beyond20/assets/5908933/5fed91f0-176c-48b4-a972-3e19a0ce3066)

**To Reproduce**
1. Go to 'Collections' > 'My Encounters'
2. Click on 'Create New'
3. Add 1 'Ogremoch' to the encounter, then add 1 'Flail Snail' (works with both the legacy version and the MoM one)
4. Click on 'Save'
5. Click on 'Ogremoch', verify the description of its "Summon Elementals" ability
6. Click on 'Flail Snail'
7. Click on 'Ogremoch' again
8. See the description of its "Summon Elementals" ability has changed
9. Disable the extension and repeat steps 5 to 8 to see this does not happen with the extension off

**Expected behavior**
The ability should always be the same, no matter what other creatures I look at beforehand.

**Browser Info (please complete the following information):**
 - Browser : Brave
 - Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)

**Comment by Aeristoka** [comment] 2023-06-04 03:12
@kakaroto loves how buggy the JS is on the Encounter Builder from DnDBeyond's side

**Comment by GSBicalho** [comment] 2023-06-04 03:20
I assume it brings him unbridled joy, yes

**Comment by kakaroto** [comment] 2023-06-04 20:18
There's unfortunately nothing to be done about that, as it's not a Beyond20 bug but rather a bug on D&D Beyond's side. I've already dug deep into this issue and came to the conclusion that they will sometimes mess things up when switching between monsters. 
It seems to happen whenever **any html** is changed on the page. Polluting the description is still better than when the entire page crashes. They've sometimes fixed it, then break it again. I never know what to expect, but unfortunately we can't do anything about it.
This is basically a duplicate of this issue: https://github.com/kakaroto/Beyond20/issues/917
Back then I fixed it by not modifying the page and just piggy-backing off the digital dice buttons instead, but in your screenshot, it looks like you don't have digital dice enabled, so the `+4` is not clickable, and that's why Beyond20 modified it to add the dice button to it.

**Closed by kakaroto** 2023-06-04 20:18 UTC
Labels: bug
