### ISSUE TITLE
JavaScript error with any monsters in the encounter builder

### ISSUE THREAD

**Issue by nathaniellee** [kakaroto/Beyond20#838] opened 2021-06-28 07:10 UTC
**Describe the bug**
When viewing one of your saved encounters, if you click a homebrew monster to load its statblock to the screen and then click to an official monster, the content portion of the page disappears almost entirely, leaving only a "Report feedback" button.

**To Reproduce**
1. Go to one of your saved encounters that includes at least one homebrew monster and one official monster.
2. Click on a homebrew monster to load its statblock.
3. Click on an official monster.
4. The header and footer are still there, but the content portion of the page is replaced by a "Report feedback" button.

**Expected behavior**
The official monster statblock is loaded.

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Browser Info (please complete the following information):**
 - Chrome
 - Version 91.0.4472.114 (Official Build) (x86_64)
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
The error only manifests when you have a homebrew monster statblock loaded and try to load an official monster. If you try to go from a homebrew to a homebrew, no problem. If you try to go from an official to an official, no problem. If you try to go from an official to a homebrew, no problem.

<img width="495" alt="Screen Shot 2021-06-28 at 3 07 30 AM" src="https://user-images.githubusercontent.com/914872/123594746-1621bd00-d7be-11eb-97f6-7cd391e97851.png">

<img width="874" alt="Screen Shot 2021-06-28 at 3 09 18 AM" src="https://user-images.githubusercontent.com/914872/123594902-41a4a780-d7be-11eb-99d0-8c46bd539ebd.png">

**Comment by Aeristoka** [comment] 2021-06-28 17:01
Duplicate of #809

**Comment by amenokos** [comment] 2021-07-19 04:10
I experienced this issue myself this evening, but my encounter did **NOT** have any homebrew monsters. It had 12 zombies and 1 evil mage. The Combat Tracker would crash when I'd select a monster to bring up its stat block, but it wouldn't happen every time, just some of the time.

The screen would go blank with _Report feedback_ shown in the upper-left corner.

![image](https://user-images.githubusercontent.com/69495414/126101503-5e40ab6d-2aa0-410d-a730-c705e20ee8d4.png)

Here's what was shown on my dev console when the tracker crashed.

![image](https://user-images.githubusercontent.com/69495414/126101597-86d44876-ea0e-4408-8112-bd07f3776f7d.png)

**Comment by Aeristoka** [comment] 2021-07-19 04:23
> I experienced this issue myself this evening, but my encounter did **NOT** have any homebrew monsters. It had 12 zombies and 1 evil mage. The Combat Tracker would crash when I'd select a monster to bring up its stat block, but it wouldn't happen every time, just some of the time.
> 
> The screen would go blank with _Report feedback_ shown in the upper-left corner.
> 
> ![image](https://user-images.githubusercontent.com/69495414/126101503-5e40ab6d-2aa0-410d-a730-c705e20ee8d4.png)
> 
> Here's what was shown on my dev console when the tracker crashed.
> 
> ![image](https://user-images.githubusercontent.com/69495414/126101597-86d44876-ea0e-4408-8112-bd07f3776f7d.png)

Same issue, just means DnDBeyond is screwing themselves more and more and regressing their code.

**Comment by amenokos** [comment] 2021-07-19 19:12
I did some additional testing.

1. Clicking a monster tile in the turn order brings up its stat block on the right (normal behavior).
2. Clicking the same tile will hide the stat block (normal behavior).
3. If the stat block of the Evil Mage is shown, and I click one of the Zombie tiles, the tracker crashes.
4. If the stat block of the Evil Mage is hidden, and I click one of the Zombie tiles, the tracker is fine.

I decided to add a Spider to the encounter. 

5. If the stat block of the Spider is shown, and I click one of the Zombie tiles, the tracker is fine.
6. If the stat block of the Evil Mage is shown, and I click the Spider tile, **the tracker is fine**.
7. If the stat block of the Evil Mage is shown, and I click one of the Zombie tiles, **the tracker crashes** as before. 

The issue for me seems to be related to the Evil Mage, but only when moving from the Mage to a Zombie, and only when the stat block of the Evil Mage is displayed. I think it might be important to note that, while the Evil Mage is not a homebrew monster, it comes from an adventure (Lost Mines of Phandelver) and not a sourcebook such as PHB or MM.

![image](https://user-images.githubusercontent.com/69495414/126213756-39c9111c-8464-4817-9b07-dd69e122f6bd.png)

**Comment by Aeristoka** [comment] 2021-07-19 21:00
> I did some additional testing.
> 
> 1. Clicking a monster tile in the turn order brings up its stat block on the right (normal behavior).
> 2. Clicking the same tile will hide the stat block (normal behavior).
> 3. If the stat block of the Evil Mage is **shown**, and I click one of the Zombie tiles, the tracker crashes.
> 4. If the stat block of the Evil Mage is **hidden**, and I click one of the Zombie tiles, **the tracker is fine**.
> 
> I decided to add a Spider to the encounter.
> 
> 1. If the stat block of the Spider is shown, and I click one of the Zombie tiles, the tracker is fine.
> 2. If the stat block of the Evil Mage is shown, and I click the **Spider** tile, **the tracker is fine**.
> 3. If the stat block of the Evil Mage is shown, and I click one of the **Zombie** tiles, **the tracker crashes** as before.
> 
> The issue for me seems to be related to the Evil Mage, but only when moving from the Mage to a Zombie, and only when the stat block of the Evil Mage is displayed. I think it might be important to note that, while the Evil Mage is not a homebrew monster, it comes from an adventure (Lost Mines of Phandelver) and not a sourcebook such as PHB or MM.
> 
> ![image](https://user-images.githubusercontent.com/69495414/126213756-39c9111c-8464-4817-9b07-dd69e122f6bd.png)

I'd suggest you bring that to DnDBeyond in any threads about this, as it has to do with them adding/removing their Digital Dice Roll buttons, and they need to get that fixed.

**Comment by amenokos** [comment] 2021-07-20 04:31
I reported this within their feedback channel on Discord and was told by a moderator that I should report the issue here because the problem with the combat tracker crashing does not occur when the Beyond 20 extension is disabled. It would seem we're at an impasse. :(

**Comment by kakaroto** [comment] 2021-07-20 07:57
> I reported this within their feedback channel on Discord and was told by a moderator that I should report the issue here because the problem with the combat tracker crashing does not occur when the Beyond 20 extension is disabled. It would seem we're at an impasse. :(

Here, you can show them how **without Beyond20 extension enabled**, the simple act of modifying one of the html paragraphs and adding an html node to it will cause the crash within the D&D Beyond's code itself. There is nothing Beyond20 could do to prevent it (other than not modifying the statblock in any way). It's a bug from there side, which Beyond20 is only making evident : 
![ddb-crash](https://user-images.githubusercontent.com/27990/126283195-f9638211-d26a-4500-b069-5d469f868d58.gif)

I will reach out from my side to another dev contact I have with DDB, to see if they can expedite accepting/handling this issue.

**Comment by amenokos** [comment] 2021-07-20 18:05
> I will reach out from my side to another dev contact I have with DDB, to see if they can expedite accepting/handling this issue.

Thank you! The workaround, for now, I think, is to click the monster tile in the turn order to hide the stat block before moving to another monster.

**Comment by amenokos** [comment] 2021-07-23 00:41
During the Dev Update this morning, they indicated that the auto-save feature for the Combat Tracker would be completed before the next Dev Update, so within the week. Perhaps it won't be so bad, now, when the tracker crashes. LOL

**Comment by markusdf** [comment] 2022-01-08 07:28
So, this issue still occurs, and is easy to recreate.
1) enable "Replace Dices formulas in D&D Beyond (Stat blocks)" in beyond20 advanced options
2) open an encounter in dndbeyond that contains at least 2 monsters with actions (e.g. bandit, and goblin boss)
3) click on bandit (so the stat block displays)
4) click on goblin boss (so the stat block displays)
5) click on bandit a second time, and the error is guaranteed to show

the work around to stop this is to disable "Replace Dices formulas in D&D Beyond (Stat blocks)" in beyond20 advanced options

**Comment by kakaroto** [comment] 2022-11-13 02:12
This issue doesn't happen anymore (tested today to make sure) as D&D Beyond have apparently fixed it! 🥳 
I think it's safe to finally close the issue. We've kept it open only for other people to see it rather than posting duplicate bug reports; this isn't necessary anymore.

**Closed by kakaroto** 2022-11-13 02:12 UTC
Labels: bug, duplicate, wontfix, D&D Beyond
