### ISSUE TITLE
Advantage/Disadvantage via shift and ctrl keys are unreliable.

### ISSUE THREAD

**Issue by andrewmadden** [kakaroto/Beyond20#338] opened 2020-06-03 02:09 UTC
Advantage and disadvantage states get stuck on, and requires clicking then moving mouse from element to remove. 

Propose using different key events for these triggers. Or perhaps a global key up event for shift and ctrl that will clear disadvantage and advantage state.

**Comment by Aeristoka** [comment] 2020-06-03 02:14
I believe this has been properly addressed in 2.0, which is currently in Google's hands for review on the Chrome Store.

**Comment by andrewmadden** [comment] 2020-06-03 02:17
I just tested in 2.0 as I was hoping this would be the case. 
![ad-dis](https://user-images.githubusercontent.com/36656753/83588159-1e480280-a594-11ea-89cb-c92a56b14dcd.gif)

**Comment by kakaroto** [comment] 2020-06-03 03:18
The shift/ctrl is already a global key event. Never had any issues with it, it was only getting stuck in the case of the Alt key binding because of people doing Alt-Tab and it would register the Alt key down, but not the Alt key up (since it happened in another tab). I've added a change to make sure all modifiers are cleared when the tab loses focus which fixed that.
Your last message with regards to 2.0 doesn't actually tell me if you consider it fixed or not (and I have no idea what to look for in that gif since I don't know when you're pressing/releasing any of the keys)..
Regardless, I don't see how it should ever get stuck and not sure why it's doing it for you. Issue #120 should resolve your problem though once it's implemented.

**Comment by andrewmadden** [comment] 2020-06-03 03:43
I guess #120 would be a workaround assuming it's not implemented in the same way the ad/dis keys currently are. 

I do not consider it fixed in 2.0.

Browser: Firefox 76.0.1

Expected behaviour:
1. When hovering over rollable stat, with no keys pressed, normal roll selected.
2. When hovering over rollable stat, with shift pressed down, advantage roll selected.
3. When hovering over rollable stat, with ctrl pressed down, disadvantage roll selected.
4. When moving from somewhere else onto rollable stat with no key held down, normal roll selected.

Actual behaviour:
1a. If no key has been pressed, normal roll is shown. 
1b. If shift has been pressed then released, advantage roll is shown.
1c. If ctrl has been pressed then released, disadvantage roll is shown.
1d. If shift if pressed, then released then pressed down, normal roll is shown.
2 & 3. Depending on which key has last pressed and released, changes what will be shown.
4a. If the last key to be pressed and released was shift, advantage will be shown.
4b. If the last key to be pressed and released was ctrl, disadvantage will be shown.

**Comment by andrewmadden** [comment] 2020-06-03 04:17
You can also see that when hovering, the roll prompt corresponds to the skill below the one being hovered over. Is this deliberate to not obscure the skill text or an error with tracking the array?

**Comment by kakaroto** [comment] 2020-06-03 04:17
Yeah, I'm not sure how you're getting that behavior but I just tested on chrome and Firefox (77.0) and the expected behavior is what I'm getting on both browsers . And considering so far you're the only one that has reported this kind of issue, I would assume for the moment that it's something weird with your install or keyboard or something like that. Without having the ability to reproduce it, there's really not much I can do.
If you have any programming knowledge, you may be able to try and debug it and figure out what's happening here for you. I'd first try to upgrade firefox just in case though.

While testing, I did notice though that if you have your rolls set to always roll with advantage (or roll twice or anything else basically), then pressing shift and releasing it will always revert the icon to the normal roll icon rather than reverting it to the icon representing your selected setting (rolling still respects the setting though).

One thing you could try, is instead of focusing on "what is shown", maybe you can tell us "what is rolled" because if it shows advantage but rolls normal, then it means the key binding is correct, it's the setting of the class that is failing. but if it rolls advantage, it means it's not even detecting the keydown event. Also check your extensions and make sure that : 
1 - you don't have 2 versions of Beyond20 installed (official release and dev mode)
2 - you don't have some other addons that could be interfering with this

**Comment by kakaroto** [comment] 2020-06-03 04:22
> You can also see that when hovering, the roll prompt corresponds to the skill below the one being hovered over. Is this deliberate to not obscure the skill text or an error with tracking the array?

No, but this started today shortly after release, it's because of the odysee ad banner at the top of the page from D&D Beyond, click 'dismiss' and they'll line up now.

**Comment by andrewmadden** [comment] 2020-06-03 04:28
I'll disable other extensions to see if any are causing an issue, and update firefox, though I doubt a single version difference would have such different results.

I'll try and debug it a bit and see what I come up with. I tracked the clicks in the console, and the requests were corresponding with what icon is shown. 

I have only the stable release of the plugin installed.

I believe my other campaign members also had this issue (in the previous Beyond20 release) but will confirm again when we meet up on Sunday.

Thanks for getting back to me about this btw.

**Comment by andrewmadden** [comment] 2020-06-03 05:02
Found the main culprit. The extension AdBlock Plus caused the worst of the behaviour, even if disabled for a site. Needed to completely disable the plugin in the browser. Behaviour persisted with Firefox 77.0.

I still can replicate a part of the issue with Firefox 77.0 that only has Beyond20 enabled.

If you move off of the 'rollable element' before releasing a key, when you move over the element again without a key pressed, it will still have the state of the key that was pressed down when leaving the element. 
1. Hover over skill.
2. Press shift.
3. Move mouse off skill with shift held down.
4. Release key. 
5. Move mouse over skill with no keys held down.
6. Roll will have advantage when clicked.

This is not game breaking for me as the previous behaviour was so would be happy for you to close this issue if you want.

**Comment by andrewmadden** [comment] 2020-06-03 05:26
Captured with keypresses in console. You can see the ad/dis states persist after the key is released.

![key-presses](https://user-images.githubusercontent.com/36656753/83598985-7855c180-a5ae-11ea-89dc-3a5f88622cab.gif)

**Comment by DarrynGlass** [comment] 2020-06-06 23:31
> The shift/ctrl is already a global key event. Never had any issues with it, it was only getting stuck in the case of the Alt key binding because of people doing Alt-Tab and it would register the Alt key down, but not the Alt key up (since it happened in another tab). I've added a change to make sure all modifiers are cleared when the tab loses focus which fixed that.

I have 2.0 installed and still have an issue with the ALT key.  After pressing the ALT key, SHIFT and CTRL no longer will add AD/DIS to the roll.  I have to click on a blank area of the page it seems to be able to re-enable the SHIFT and CTRL.

**Comment by kakaroto** [comment] 2020-06-08 18:34
> I have 2.0 installed and still have an issue with the ALT key. After pressing the ALT key, SHIFT and CTRL no longer will add AD/DIS to the roll. I have to click on a blank area of the page it seems to be able to re-enable the SHIFT and CTRL.

That's because ALT opens the menu in your browser (press down arrow afterwards, you'll see) so the focus moves to the menu that is now selected. The ALT behavior only works if you press ALT and click at the same time. There's nothing that can be done about it, and I chose Alt for the 'normal roll' specifically because of this problem, as I consider 'normal' will be the least used modifier.

**Comment by DarrynGlass** [comment] 2020-06-11 17:46
Thank you that makes sense.

**Comment by Aeristoka** [comment] 2020-09-29 04:28
Should be closed.

**Comment by kakaroto** [comment] 2020-09-29 04:40
I thought I just closed it earlier this week.... looks like I'm going senile!
Closing as I think this is all fixed, if it's not, feel free to re-open with more details @andrewmadden 
Thanks!

**Closed by kakaroto** 2020-09-29 04:40 UTC
