### ISSUE TITLE
Using HotKeys

### ISSUE THREAD

**Issue by AGoudreault** [kakaroto/Beyond20#651] opened 2021-01-13 18:08 UTC
**Describe the bug**
Adding a HotKey (say, “h” for Warlock HexBlaDe Curse activation) creates the entry, displays it when clicking on the Beyond20 title button, but using the state key (“h”) produces nothing, not even a toggle within the Beyond20 title button options list

**To Reproduce**
1. Add HotKey (“h” ; Hexblade Curse)
2. Press “h” then attack - no difference in attack, toggle not set
3. Hold “h” then attack - cannot use Beyond20 attack button while holding letter

**Expected behavior**
A toggle, with indication of activation/deactivation, along with stated effects ported/shown unto VTT screen

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Browser Info (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 85]
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by Aeristoka** [comment] 2021-05-06 20:20
I can't replicate this on 2.4.1.

Normal behavior:
Press and HOLD h key + click attack: Rolls fine.

There is also the Sticky Hotkeys that can be used now:
![image](https://user-images.githubusercontent.com/7988297/117360533-25e3eb80-ae76-11eb-8fe6-70af38a2726c.png)

**Comment by kakaroto** [comment] 2021-05-29 05:30
I think it's a duplicate of #753 which was fixed with a905dfa
The issue was the hotkey was getting ignored if it was pressed while hovering.
As for the suggestion to show the hotkeys that are enabled, this has been added already in the 2.4.0 release

**Closed by kakaroto** 2021-05-29 05:30 UTC
Labels: bug
