### ISSUE TITLE
Rolls not displaying in Chat on Roll20

### ISSUE THREAD

**Issue by treed593** [kakaroto/Beyond20#211] opened 2020-04-20 01:14 UTC
When any player uses Beyond20 to roll from DNDBeyond, to Roll20 their roll is submitted and we can see their name in chat, but cannot see their roll (not even the DM), initiative Rolls are still submitted to the turn tracker though.

![image](https://user-images.githubusercontent.com/6807466/79705202-d0489b00-8282-11ea-9f70-20f36ebc75d9.png)

**Comment by Aeristoka** [comment] 2020-04-20 01:16
https://beyond20.here-for-more.info/faq#all-i-see-in-roll20-is-an-empty-message

Duplicate of #161

**Closed** 2020-04-20 01:46 UTC
