### ISSUE TITLE
DDB Encounter Builder issue

### ISSUE THREAD

**Issue by protoclown11** [kakaroto/Beyond20#1011] opened 2022-08-16 05:36 UTC
When accessing DDB's My Encounters and clicking on the monsters in the Monsters list before hitting Run Encounter, the page will sometimes go blank below the top menu on the page. It seems to happen at random times on random monsters, but it eventually happens after clicking on 3-4 monsters. I have to refresh the page to get the list back. If I turn off Beyond20, this behavior stops.
![Screenshot 2022-08-16 013613](https://user-images.githubusercontent.com/10471624/184805456-7a12c52b-1554-47f0-8003-cdb09b020c07.jpg)

**Comment by Aeristoka** [comment] 2022-08-16 12:08
See https://github.com/kakaroto/Beyond20/issues/838#issuecomment-883182978

Duplicate of #838

**Closed by Aeristoka** 2022-08-16 12:08 UTC
