### ISSUE TITLE
Symbiotic Entity doesn't work

### ISSUE THREAD

**Issue by stevethorson** [kakaroto/Beyond20#681] opened 2021-02-03 21:53 UTC
I have a Circle of Spores Druid. In the Character Specific Options section of the settings, there is a switch for Circle of Spores: Symbiotic Entity. Turning it on doesn't seem to do anything. 

I expect it to double my dice for Halo of Spores, and add 1d6 necrotic damage to my melee attacks.

**Comment by Aeristoka** [comment] 2021-02-03 21:55
The melee part works, I just tested it.

**Comment by Aeristoka** [comment] 2021-02-03 22:13
Alright @stevethorson PR in to address the Halo of Spores. I hadn't done that initially, assuming people would just roll them twice, but there is the code now.

The Melee Attacks worked fine for me, so if you can offer a screenshot of proof otherwise I can look into it.

**Comment by stevethorson** [comment] 2021-02-03 22:20
Thank you for such a quick response! I just tested with a different weapon and realized that it works on my scimitar... However, I use a custom melee weapon, and it does not work on that.

**Comment by Aeristoka** [comment] 2021-02-03 22:20
> Thank you for such a quick response! I just tested with a different weapon and realized that it works on my scimitar... However, I use a custom melee weapon, and it does not work on that.

Do you have a screenshot of it? or an example character sheet? I have a fair guess as to what is wrong with it.

**Comment by stevethorson** [comment] 2021-02-03 22:24
what would you like me to take a screenshot of?
The weapon not including the damage in roll20? or do you want a screenshot of the settings on the weapon?
This is the character sheet. The problematic weapon is the pick mattock.
https://ddb.ac/characters/41541866/0hrLdY

**Comment by stevethorson** [comment] 2021-02-03 22:25
Screenshot of weapon setup.
<img width="320" alt="Screen Shot 2021-02-03 at 5 24 49 PM" src="https://user-images.githubusercontent.com/750906/106817403-d1e22480-6644-11eb-9a68-e36d230fcf49.png">

**Comment by Aeristoka** [comment] 2021-02-03 22:26
> what would you like me to take a screenshot of?
> The weapon not including the damage in roll20? or do you want a screenshot of the settings on the weapon?
> This is the character sheet. The problematic weapon is the pick mattock.
> https://ddb.ac/characters/41541866/0hrLdY

Alright, found the issue:
Scimitar:
![image](https://user-images.githubusercontent.com/7988297/106817366-000b3880-6634-11eb-9527-f7a1d41f317c.png)

As you can see, it is an item, and has the "Melee" characteristic.

The custom "Weapon" you made is a duplicate of an Unarmed Strike, which isn't technically a "weapon", you'll need to make an Item and equip it.
![image](https://user-images.githubusercontent.com/7988297/106817509-3052d700-6634-11eb-9b2d-572c7c6cf260.png)

**Comment by stevethorson** [comment] 2021-02-03 22:33
Oh. Thank you. I removed "Natural Attack", and that didn't help. But I suppose you would have expected that based on your response.
There doesn't seem to be any other way to make weapons in dndbeyond. So I guess I'm out of luck there?
Thanks so much for your time and quick responses. I really appreciate it, and love what you've made.

**Comment by Aeristoka** [comment] 2021-02-03 22:40
https://www.dndbeyond.com/my-collection

Go create a homebrew item. THAT is the way to make Items in DnDBeyond. What you made is a "Custom Action".

**Comment by stevethorson** [comment] 2021-02-03 22:46
Ok. Thanks so much.

**Closed** 2021-02-04 21:12 UTC
