### ISSUE TITLE
No crit damage possible 

### ISSUE THREAD

**Issue by phookade** [kakaroto/Beyond20#1183] opened 2024-10-30 14:19 UTC
**Describe the bug**
Whenever the addon is active, the damage dice are no longer doubled in DnDBeyond. Therefore, no crit dice are actually rolled, the additional dice have to be rolled manually. Homebrew options are neither needed by us nor used.

**To Reproduce**
1. Roll attacks until a crit happens
2. look at the field for damage dice, they are unchanged.

**Expected behavior**
Just as with the addon disabled, the damage dice should be doubled (e.g. 1D6+1 -> 2D6+1)

**Browser Info (please complete the following information):**
 - firefox
 - Version 132.0

**Comment by dmportella** [comment] 2024-10-30 14:44
crit damages are working on 2.9.8

![image](https://github.com/user-attachments/assets/351453d1-0019-4520-9941-bdf1f31da87a)

What version of the extension are you using can you provide screenshots, for the roles, and the console window too to see if there is any errors

could you also provide a link to the testing character you are using (make sure it is set to public)

**Comment by phookade** [comment] 2024-10-30 15:37
addon is on 2.9.8

Issue is that the D&D Beyond character sheet _itself_ does not double damage dice anymore. I do not let the addon roll damage, I do so manually. You get a screenshot where a crit was just rolled, the damage die is not doubled, in Roll20, it's marked green to signify a crit. I also attach the complete console log as text since I don't know what part you need.
![CritNoAddDamagaDie](https://github.com/user-attachments/assets/6721166f-61c3-4546-9128-41c4513fe0bc)
[console_complete.txt](https://github.com/user-attachments/files/17575419/console_complete.txt)

**Comment by dmportella** [comment] 2024-10-30 16:18
Check my annotated image

![image](https://github.com/user-attachments/assets/2f821655-576f-49c5-bc97-04287fe5f1f3)

**Comment by dmportella** [comment] 2024-10-30 16:20
Rolling for attack separately and then rolling for the damage on the sheet it does not track if it the previous roll was a critical.

It never did, never was supported,

The Options you have are:

1 - Pressing the action icon that rolled everything 
2 - Roll for attack on dnd beyond and then Press the Pink button on roll20 to roll the Damage

**Comment by kakaroto** [comment] 2024-10-30 18:36
Other option I know some people use, would be to create a hotkey for 'roll critical' and use that hotkey when clicking the damage button, but as @dmportella said, the correct way of doing it would be to click the "roll damages" button in the VTT for the attack roll that you did which rolled critical. D&D Beyond and Beyond20 have no way of knowing whether the attack was a crit or not once it's been sent over to be rolled on the VTT's side.
Closing as invalid, since that's the expected behavior and anything different would not make sense either.

**Closed by kakaroto** 2024-10-30 18:36 UTC
Labels: invalid
