### ISSUE TITLE
Beyond20 needs an update for the new Roll20 API.

### ISSUE THREAD

**Issue by SirRaiuKoren** [kakaroto/Beyond20#605] opened 2020-12-06 00:56 UTC
Title. Roll20 changed its api formatting sometime within the past few days and Beyond 20 needs updating. Thanks!

**Comment by Aeristoka** [comment] 2020-12-06 01:05
Duplicate of #592 and #593 and #594 and #595 and #603 

Fixed in the Dev version: https://github.com/kakaroto/Beyond20#developer-mode-installation
See also the Beyond20 Discord for another workaround: https://discord.gg/WGNSHcGNRB

Please close.

**Closed** 2020-12-06 01:06 UTC
