### ISSUE TITLE
Extension not working with Foundry v9 (Fixed in dev)

### ISSUE THREAD

**Issue by Kheldarek** [kakaroto/Beyond20#903] opened 2021-12-21 22:27 UTC
**Describe the bug**
Hi, i cant get this extension to work in new stable 0.9.9 version.  When i click to do any roll on dndbeyond page, they are not rolled in foundry.

**To Reproduce**
1. Open foundry in latest stable version
2. Open a character sheet in  dnd beyond
3. Try to roll any check
4. See that nothing happens in Foundry

**Expected behavior**
I expect to have the check rolled in Foundry

**Screenshots**
There are some errors in console: 
![image](https://user-images.githubusercontent.com/9088256/147005198-55f306ac-eb0d-4584-a442-1b725c142a89.png)

**Browser Info (please complete the following information):**
Latest Chrome. Errors are on thge screenshot above, but im also uploading exported logs if its helpfull for you. 
[213.146.42.134-1640125374397.log](https://github.com/kakaroto/Beyond20/files/7758687/213.146.42.134-1640125374397.log)

**Additional context**

**Comment by Aeristoka** [comment] 2021-12-21 22:37
Already fixed in the Dev Version:
https://github.com/kakaroto/Beyond20/commit/8d5d4a021968f9feab88d1afa3ef20a53f28b0fd
https://github.com/kakaroto/Beyond20/commit/674f47f0494ead17d3efb8e1ac2161a9b60277dd

Install using this:
https://github.com/kakaroto/Beyond20#developer-mode-installation

Full release still pending.

**Comment by Aeristoka** [comment] 2021-12-21 22:37
Re-opened to try to catch other people coming with this issue

**Comment by curtisshipley** [comment] 2021-12-24 21:37
How long until the full release will be available?

**Comment by kakaroto** [comment] 2021-12-25 18:59
> How long until the full release will be available?

No specific ETA but I'm trying to get it out before the new year. Doing my best to work on B20 and add more fixes/features before doing a release, but between the holidays and my own need to rest and not burnout, I don't want to make any promises at this time.

**Comment by curtisshipley** [comment] 2021-12-25 19:01
@kakaroto Thank you. I appreciate that. I, too, am a software engineer. Anything I can do to help?

**Comment by kakaroto** [comment] 2021-12-25 21:17
> @kakaroto Thank you. I appreciate that. I, too, am a software engineer. Anything I can do to help?

Thanks for proposing, I'd happily accept help if you are willing to provide it. You can see the 2.6 milestone (https://github.com/kakaroto/Beyond20/milestone/17) and if there's any issue you're interested in working on, feel free to comment on the issue (so we don't both work on the same thing) and send a PR with the changes if you manage to do it.
Poke me on Discord too if you need help or to sync up.
Thanks!

**Comment by LozoTrioxide** [comment] 2022-01-04 18:08
I am also having the same trouble as OP, except im using the beta version and its still not going to Foundry. Ive made sure they're both enabled on chrome, but there isnt any errors, it just doesnt do anything.

**Comment by Celludriel** [comment] 2022-01-04 18:12
Any chance you can open a new branch from the current stable version and fix and release just the fix for v9 and keep the new features in a seperate branch you release on a later date ?  Feels like this fix is a bit more critical then any other features or fixes ?

**Comment by Aeristoka** [comment] 2022-01-04 18:13
> I am also having the same trouble as OP, except im using the beta version and its still not going to Foundry. Ive made sure they're both enabled on chrome, but there isnt any errors, it just doesnt do anything.

The Dev version 100% works with FoundryVTT v9, myself and 7 players ran 5.5 hours of play on Saturday with it. Make sure you follow the install instructions to the letter: https://github.com/kakaroto/Beyond20#developer-mode-installation

AND

Grab a new version NOW, there were some fixes for things being a little broken due to some code changes, it's possible you have that version.

**Comment by Aeristoka** [comment] 2022-01-04 18:14
> Any chance you can open a new branch from the current stable version and fix and release just the fix for v9 and keep the new features in a seperate branch you release on a later date ? Feels like this fix is a bit more critical then any other features or fixes ?

That's not something that is going to happen honestly. The Dev version is 100% usable with v9 (see my above comment), and the release is looking good for today with v9 support + features.

**Comment by curtisshipley** [comment] 2022-01-04 19:57
It is not working for me on Chrome either. (It does work on firefox.)   

Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.

Debug console output:

```
Beyond20: Executing panel : ct-skill-pane false false
dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
```

**Comment by Aeristoka** [comment] 2022-01-04 19:58
> It is not working for me on Chrome either. (It does work on firefox.)
> 
> Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> 
> Debug console output:
> 
> ```
> Beyond20: Executing panel : ct-skill-pane false false
> dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> ```

grab the console output from the FoundryVTT Tab, not the DnDBeyond tab.

**Comment by Aeristoka** [comment] 2022-01-04 20:02
> It is not working for me on Chrome either. (It does work on firefox.)
> 
> Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> 
> Debug console output:
> 
> ```
> Beyond20: Executing panel : ct-skill-pane false false
> dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> ```

@kakaroto I actually just replicated this on a local install of FoundryVTT.

**Comment by curtisshipley** [comment] 2022-01-04 20:03
> > It is not working for me on Chrome either. (It does work on firefox.)
> > Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> > Debug console output:
> > ```
> > Beyond20: Executing panel : ct-skill-pane false false
> > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> > ```
> 
> grab the console output from the FoundryVTT Tab, not the DnDBeyond tab.

There isn't any output. (Maybe I'm doing it wrong?) Here's what I did:

1. Have Foundary VTT in a tab and DNDBeyond in a Tab. I've made sure to activate the plugin while on the VTT page so the red dice is showing in the comment side-bar in VTT.
2. Open developer tools while I'm on the Foundry tab.
3. Switch back to DNDBeyond. Do a dice roll.
4. Nothing shows in console output.

**Comment by Aeristoka** [comment] 2022-01-04 20:04
> > > It is not working for me on Chrome either. (It does work on firefox.)
> > > Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> > > Debug console output:
> > > ```
> > > Beyond20: Executing panel : ct-skill-pane false false
> > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> > > ```
> > 
> > 
> > grab the console output from the FoundryVTT Tab, not the DnDBeyond tab.
> 
> There isn't any output. (Maybe I'm doing it wrong?) Here's what I did:
> 
> 1. Have Foundary VTT in a tab and DNDBeyond in a Tab. I've made sure to activate the plugin while on the VTT page so the red dice is showing in the comment side-bar in VTT.
> 2. Open developer tools while I'm on the Foundry tab.
> 3. Switch back to DNDBeyond. Do a dice roll.
> 4. Nothing shows in console output.

You might've actually stumbled into something here, I had run my session against a full URL based FoundryVTT server, not a local install. The fact that it shows that error on DnDBeyond and nothing on FoundryVTT is 100% relevant and good info.

**Comment by curtisshipley** [comment] 2022-01-04 20:05
> > > > It is not working for me on Chrome either. (It does work on firefox.)
> > > > Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> > > > Debug console output:
> > > > ```
> > > > Beyond20: Executing panel : ct-skill-pane false false
> > > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > > dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> > > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > > 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> > > > ```
> > > 
> > > 
> > > grab the console output from the FoundryVTT Tab, not the DnDBeyond tab.
> > 
> > 
> > There isn't any output. (Maybe I'm doing it wrong?) Here's what I did:
> > 
> > 1. Have Foundary VTT in a tab and DNDBeyond in a Tab. I've made sure to activate the plugin while on the VTT page so the red dice is showing in the comment side-bar in VTT.
> > 2. Open developer tools while I'm on the Foundry tab.
> > 3. Switch back to DNDBeyond. Do a dice roll.
> > 4. Nothing shows in console output.
> 
> You might've actually stumbled into something here, I had run my session against a full URL based FoundryVTT server, not a local install. The fact that it shows that error on DnDBeyond and nothing on FoundryVTT is 100% relevant and good info.

I'm using this against a server install of VTT and not a local one.

**Comment by Aeristoka** [comment] 2022-01-04 20:06
> > > > > It is not working for me on Chrome either. (It does work on firefox.)
> > > > > Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> > > > > Debug console output:
> > > > > ```
> > > > > Beyond20: Executing panel : ct-skill-pane false false
> > > > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > > > dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> > > > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > > > 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> > > > > ```
> > > > 
> > > > 
> > > > grab the console output from the FoundryVTT Tab, not the DnDBeyond tab.
> > > 
> > > 
> > > There isn't any output. (Maybe I'm doing it wrong?) Here's what I did:
> > > 
> > > 1. Have Foundary VTT in a tab and DNDBeyond in a Tab. I've made sure to activate the plugin while on the VTT page so the red dice is showing in the comment side-bar in VTT.
> > > 2. Open developer tools while I'm on the Foundry tab.
> > > 3. Switch back to DNDBeyond. Do a dice roll.
> > > 4. Nothing shows in console output.
> > 
> > 
> > You might've actually stumbled into something here, I had run my session against a full URL based FoundryVTT server, not a local install. The fact that it shows that error on DnDBeyond and nothing on FoundryVTT is 100% relevant and good info.
> 
> I'm using this against a server install of VTT and not a local one.

what URL/IP do you use to connect though?

**Comment by curtisshipley** [comment] 2022-01-04 20:07
> > > > > > It is not working for me on Chrome either. (It does work on firefox.)
> > > > > > Fresh install of plugin as of 20 min ago. Foundry version 9/ build 238.
> > > > > > Debug console output:
> > > > > > ```
> > > > > > Beyond20: Executing panel : ct-skill-pane false false
> > > > > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > > > > dndbeyond_character.js:4174 Sending message:  {action: 'roll', character: {…}, type: 'skill', roll: '1d20+4', advantage: 0, …}
> > > > > > dndbeyond_character.js:8124 Beyond20: New side panel is : ct-skill-pane
> > > > > > 19516511:1 Unchecked runtime.lastError: The message port closed before a response was received.
> > > > > > ```
> > > > > 
> > > > > 
> > > > > grab the console output from the FoundryVTT Tab, not the DnDBeyond tab.
> > > > 
> > > > 
> > > > There isn't any output. (Maybe I'm doing it wrong?) Here's what I did:
> > > > 
> > > > 1. Have Foundary VTT in a tab and DNDBeyond in a Tab. I've made sure to activate the plugin while on the VTT page so the red dice is showing in the comment side-bar in VTT.
> > > > 2. Open developer tools while I'm on the Foundry tab.
> > > > 3. Switch back to DNDBeyond. Do a dice roll.
> > > > 4. Nothing shows in console output.
> > > 
> > > 
> > > You might've actually stumbled into something here, I had run my session against a full URL based FoundryVTT server, not a local install. The fact that it shows that error on DnDBeyond and nothing on FoundryVTT is 100% relevant and good info.
> > 
> > 
> > I'm using this against a server install of VTT and not a local one.
> 
> what URL/IP do you use to connect though?

I've set up a domain name, hosting on nginx -> vtt.

**Comment by Aeristoka** [comment] 2022-01-04 20:08
but you have to click on the Beyond20 icon to activate on the FoundryVTT tab, right? that's the most relevant info.

**Comment by curtisshipley** [comment] 2022-01-04 20:13
> but you have to click on the Beyond20 icon to activate on the FoundryVTT tab, right? that's the most relevant info.

Yes, I click on the dice. Also, I've disabled all other extensions except for Beyond20 and still get the same behavior.

**Comment by Aeristoka** [comment] 2022-01-04 20:14
> > but you have to click on the Beyond20 icon to activate on the FoundryVTT tab, right? that's the most relevant info.
> 
> Yes, I click on the dice. Also, I've disabled all other extensions except for Beyond20 and still get the same behavior.

@kakaroto and I are hunting this out right now, appreciate the detailed info to help us suss out this bug.

**Comment by curtisshipley** [comment] 2022-01-04 20:19
> > > but you have to click on the Beyond20 icon to activate on the FoundryVTT tab, right? that's the most relevant info.
> > 
> > 
> > Yes, I click on the dice. Also, I've disabled all other extensions except for Beyond20 and still get the same behavior.
> 
> @kakaroto and I are hunting this out right now, appreciate the detailed info to help us suss out this bug.

Sure thing. Happy to help. Let me know if there is anything else you'd like me to do.

I believe you just did another development build yesterday/today. If the previous version is available, I'd be happy to give that a try. Is that available somewhere?

Also, the version I tried with Firefox was before yesterday's update. I'll try the latest Firefox plugin, too.

**Comment by kakaroto** [comment] 2022-01-04 20:20
I can confirm and I'm currently fixing it. Something broke in a recent commit, and thank you very much for catching it before release! I was just writing the release notes! 😬

**Comment by kakaroto** [comment] 2022-01-04 20:23
I've just fixed it, so @curtisshipley if you want to redownload the dev version and try again, it should work now, thanks!

**Comment by curtisshipley** [comment] 2022-01-04 20:32
@kakaroto & @Aeristoka  Just tested the latest version and it works!  Thanks so much for promptly jumping on this!

**Comment by kakaroto** [comment] 2022-01-04 20:40
> @kakaroto & @Aeristoka Just tested the latest version and it works! Thanks so much for promptly jumping on this!

And thanks for reporting it with the debug info, that was very helpful. Now that a last-minute bug was found and fixed, I feel more confident about this release! 😁 
Glad we caught it just before the update was released. I'll go finish writing my release notes now!

**Comment by Aeristoka** [comment] 2022-01-04 20:42
> Any chance you can open a new branch from the current stable version and fix and release just the fix for v9 and keep the new features in a seperate branch you release on a later date ? Feels like this fix is a bit more critical then any other features or fixes ?

Give it a try again now, thanks to the helpful debug info from @curtisshipley we have a new fix in that might fix for you.

Release notes being written up now for full release.

**Comment by kakaroto** [comment] 2022-01-04 22:56
With v2.6.0 now released, we can close this issue, thanks!

**Closed by kakaroto** 2022-01-04 22:56 UTC
Labels: bug, FVTT
