### ISSUE TITLE
Higher level casting a spell from spells list while lower level spell sidebar is open casts at wrong level.

### ISSUE THREAD

**Issue by MicahZoltu** [kakaroto/Beyond20#467] opened 2020-07-19 23:31 UTC
![image](https://user-images.githubusercontent.com/886059/87887783-be7dbc00-ca5a-11ea-84a7-651e4932fb56.png)

As seen in the screenshot, the spell sidebar is open with Catapult set to cast at first level.  If I click on the button in the spell list to higher-level cast at 3rd level (see red circled button in screenshot), the spell is cast at 1st level in Roll20.

**Comment by Aeristoka** [comment] 2020-07-19 23:32
Duplicate of #459 and #465 (same cause)

**Comment by MicahZoltu** [comment] 2020-07-19 23:34
@Aeristoka I'm surprised this is the same cause as #459.  The higher-level cast buttons in that list work correctly when the sidebar panel is closed.

**Comment by Aeristoka** [comment] 2020-07-19 23:55
> @Aeristoka I'm surprised this is the same root cause as #459. The higher-level cast buttons in that list work correctly when the sidebar panel is closed.

It has to do with the changed behavior of the pop-out panel. All that happens when you click to cast is that Beyond20 opens the sidepanel, to scrape info from there (the reliable source). DnDBeyond has changed the side panel behavior recently.

**Comment by MicahZoltu** [comment] 2020-07-20 00:04
Marking this as closed under the assumption that when #465 is fixed, this will get fixed too.

**Comment by kakaroto** [comment] 2020-07-20 03:13
Reopening this issue, as I determine it's not a duplicate of #465. The issue here is that on the click to the cast button from the quick roll area, Beyond20 will trigger a click on the spell so D&D Beyond can open the sidepanel for that spell. It looks like D&D Beyond however will not reset the spell to the level where the click happened if the current side panel is already open on the same spell.
You can try this yourself, open a spell, then click on the same spell in the spell list from a different level, as long as it's the same spell name, the sidebar isn't updated. 
Beyond20 would need to detect the level it was clicked on, compare with the current sidebar level, and if they differ, force a dismissal of the side panel and *then* trigger the click to force D&D Beyond to behave properly, before it can parse the info and send the roll.

The #465 issue is about listening to the click multiple times on the same button, so it's unrelated.

**Closed** 2020-09-25 04:30 UTC
Labels: bug
