### ISSUE TITLE
Attack rolls throwing error

### ISSUE THREAD

**Issue by dcottr** [kakaroto/Beyond20#176] opened 2020-04-09 05:42 UTC
It looks like `item_name = $(".ct-item-pane .ct-sidebar__heading .ct-item-name")[0].firstChild.textContent;` is throwing an error because the class is now `. ddbc-item-name`, either DnDBeyond has changed some class names or it's going down the wrong flow I'm not sure.

This happens when I click "Beyond 20" on any equipped weapon.

<img width="1143" alt="Screen Shot 2020-04-08 at 10 41 07 PM" src="https://user-images.githubusercontent.com/2553719/78861641-1fbcda80-79ea-11ea-9c4c-1c3b7d0b639d.png">

**Comment by kakaroto** [comment] 2020-04-09 05:55
Hi,
Thanks for the report, but this is a duplicate of #174 and #175. Expect tomorrow's release to fix it, or use the development version in the meantime, or logout from D&D Beyond so you're not using the alpha sheet.
Thanks.

**Closed by kakaroto** 2020-04-09 05:55 UTC
Labels: duplicate
