### ISSUE TITLE
Dex modifier not adding to initiative rolls in roll 20

### ISSUE THREAD

**Issue by 80billion** [kakaroto/Beyond20#974] opened 2022-04-13 02:35 UTC
My entire group experienced the same issue. when we roll initiative it is not adding our dex modifier in roll 20. The formula in roll20 shows it but it isn't actually getting added.

**Comment by Aeristoka** [comment] 2022-04-13 02:38
Duplicate of https://github.com/kakaroto/Beyond20/issues/973

Fixed in Dev, release soon tonight.

**Closed by Aeristoka** 2022-04-13 02:38 UTC
