### ISSUE TITLE
Attack rolls no longer work due to D&D Beyond CSS changes

### ISSUE THREAD

**Issue by EmKayUltra** [kakaroto/Beyond20#429] opened 2020-07-08 01:14 UTC
Action: click Beyond20 attack button in D&D beyond
Expected: attack transmitted to Roll20
Actual: nothing

Upon inspecting the Console, it looks like D&D Beyond changed CSS class names for the "character class" div, and Beyond20 is still looking for the old one.  So when `hasClass(name)` is called, this._classes is null.  

The problematic piece of code is here:
```
if (this._classes === null) {
            const jClasses = $(".ct-character-tidbits__classes,.ddbc-character-tidbits__classes");
            if (jClasses.length > 0) {
                const classes = jClasses.text().split(" / ");
                this._classes = {}
                for (let class_ of classes) {
                    const parts = class_.split(" ");
                    const name = parts.slice(0, -1).join(" ");
                    const level = parts.slice(-1)[0];
                    this._classes[name] = level;
                }
            }
        }
```

The correct CSS class selector would be `.ddbc-character-summary__classes` not `.ddbc-character-tidbits__classes`

I imagine this isn't the only problem like this, but it's the first I've found.

**Comment by kakaroto** [comment] 2020-07-08 01:16
Yep, thanks for the detailed analysis.
This is a duplicate of #427 which just started happening, was reported and was fixed within the last few hours :)

**Comment by EmKayUltra** [comment] 2020-07-08 01:16
@kakaroto i'm still experiencing it literally right now

**Closed by kakaroto** 2020-07-08 01:16 UTC
Labels: duplicate

**Comment by EmKayUltra** [comment] 2020-07-08 01:17
Thanks for the timely response and fix :)
