### ISSUE TITLE
Weapon rolls and player names no longer working with D&D Beyond update

### ISSUE THREAD

**Issue by mikehdt** [kakaroto/Beyond20#432] opened 2020-07-08 09:36 UTC
Looks like D&D Beyond made a few tweaks to the page. As a result, a few things I've noticed are no longer working:

* Beyond20 options are all disabled within D&D Beyond
* Weapon attacks no longer send dice rolls
* Player names not understood, always sends rolls it can make as the default name (As: [your name])
* The character names underneath rolls are all `null`

There may be a few other things, but that's what I've noticed so far.

**Comment by kakaroto** [comment] 2020-07-08 09:43
Duplicate of #427, I'm uploading the update with the fix to chrome/firefox as we speak.

**Closed by kakaroto** 2020-07-08 09:43 UTC

**Comment by mikehdt** [comment] 2020-07-08 10:56
Fantastic! Thanks for your amazing work :)
